julia-vscode/julia-vscode

scripts/languageserver/protocol.jl, scripts/languageserver/provider_completions.jl, scripts/languageserver/provider_hover.jl
also extends completion list lengths to 25 from 10
=> Cleans up hovers and add docs to completion lists

scripts/languageserver/languageserver.jl, scripts/languageserver/protocol.jl, scripts/languageserver/provider_misc.jl, scripts/languageserver/utilities.jl
=> incremental doc sync

scripts/languageserver/protocol.jl, scripts/languageserver/provider_completions.jl, scripts/languageserver/provider_definitions.jl, scripts/languageserver/provider_diagnostics.jl, scripts/languageserver/provider_hover.jl, scripts/languageserver/provider_misc.jl, scripts/languageserver/provider_signatures.jl, scripts/languageserver/transport.jl, scripts/languageserver/utilities.jl
also removes an unused and unneeded `get_sym` method
=> General cleanup, make code style a bit more consistent

scripts/languageserver/provider_misc.jl, scripts/languageserver/utilities.jl
This fixes #57.
@ZacLN Can you check whether that also works on non-Windows?
=> Make decision whether to lint work on Windows

scripts/languageserver/provider_completions.jl
Documentation for completions need to a strings not markedstrings
=> return string for completion docs

src/extension.ts
This uses a different strategy for sending code to the REPL. It still is triggered by Ctrl+Enter.
I'm leaving the old core around as a comment, in case we figure out how to solve the julia prompt issue, I think it would be a more elegant solution. But for a v0.5 release, this should do.
@ZacLN I'll no longer commit anything to master. I'll submit everything as PRs, and I'll wait until you have reviewed everything, ok? Seems better if we follow that workflow for now, four eyes spot more errors than two.
=> Paste code to REPL

scripts/languageserver/provider_diagnostics.jl, scripts/languageserver/utilities.jl
@ZacLN can you review? Thanks!
=> Fix detection of start column for lint message

src/extension.ts
=> Restart language server when config changes

README.md
=> Add configuration explanation to README

scripts/languageserver/provider_definitions.jl
This should fix #85, I hope.
@ZacLN Can you test on a non-Windows machine, to make sure this doesn't break things there?
=> Properly encode filenames as URI

README.md
=> Add screencast links to README

scripts/languageserver/provider_completions.jl
This should fix the error in #95.
=> Convert ch index to byte index in completion

README.md, package.json, src/extension.ts
=> Add test runner command

src/extension.ts
~~Half way there, still lots of things to do before this works. Don't merge at this point.~~
=> Workspace level doc handling

.gitmodules
I need this fork of JuliaParser before adding to LS.jl, I'm unsure if this is all that needs to be done to change the version>
=> change JuliaParser version

package.json
=> Make julia keybinding only work with jl file

src/extension.ts
@ZacLN This fixes #128 on Windows, but it would be good if you could test this on Linux before we merge and release.
I'm merging this into the release-0.5 branch so that we can create a v0.5.1 bug-fix release quickly, and then I'll later merge this into master.
=> Fix whitespace path bug on Windows

.gitmodules, package.json, scripts/languageserver/main.jl, src/extension.ts
This bumps the julia requirement up to v0.6.0-  and the language server protocol to 3.0.0.
I'm having such problems removing submodules I'm going to do this in two steps, this adds CSTParser and the code change a second will remove the unneeded submodules.
=> Update language server protocol to 3.0.0

package.json
Apart from the REPL prompt (and arguably the logo) Julia is written with a capital J everywhere. Additionally most other programming languages in VS Code are written with a capital first letter.
=> Capitalise first letter of Julia name in UI

src/extension.ts
Adds client side interface for busy/ready status bar identifier. 
Replaces #192 to deal with submodule conflicts.
=> Add server status bar indicator

syntaxes/julia.json
This uses a converted version of commit 6376317 from atom-language-julia.
=> Update syntax file

src/extension.ts
Fixes #216. Copied from JuliaEditorSupport/atom-language-julia#110.
=> Fix auto indent

package.json, src/extension.ts
=> Add doc build task

README.md
=> mention auto-indentation in the Readme

package.json
=> Update minimal version for language client

README.md
=> Add complete installation instructions

julia.configuration.json
`#region` and `#endregion`.
fixes #282.
=> Support folding regions

src/extension.ts
should fix auto-fix for deprecations
=> fix applyTextEdit

src/repl.ts
There are two places where we need to display things in column 2 :)
=> Always show plot pane in right column

src/repl.ts
Fixes #293.
The behavior with this is as follows:
- executing the command "Julia: Start REPL" will give the focus to the REPL
- sending any code from an editor to the REPL will keep the focus in the document
=> Fix REPL focus handling

src/repl.ts
Fixes #359. Or at least gives a better error message.
=> Show a better error message if LS is not ready at block execute

src/extension.ts
=> Change LS statusbar label

scripts/terminalserver/terminalserver.jl
Fixes a bug found by @malmaud.
=> Fix small UI bug in REPL

src/repl.ts
Fixes a bug reported by @malmaud.
=> Show error for change REPL command without a REPL

src/extension.ts
=> Don't use red for statusbar item

package.json, src/repl.ts
Fixes #328 for v0.8.0. We can reenable in v0.9.0 once we have sorted out the timing issues.
=> Disable REPL var list for this release

syntaxes/julia.json
I just converted the atom-julia-language version again to track what they changed.
=> Update syntax file to track latest atom-language-julia version

src/tasks.ts
We should only merge this once we have released v0.8.0 final.
=> Provide multi-root support for tasks

src/weave.ts
Fix #427. The whole weave stuff was completely broken right now...
=> Fix weave commands

src/repl.ts
requires LS PR, fixes
https://github.com/JuliaEditorSupport/julia-vscode/issues/392
=> Skip trailing comments on eval block

src/extension.ts
Should fix #367 but I don't know how to test it.
=> dont steal focus by showing output

syntaxes/julia.json
Fixes #256. Just the usual copy over from the Juno grammar.
=> Update grammar file

src/weave.ts
=> Log an info message when Weave is executed

src/packagepath.ts
=> Make package path detection more robust

.gitmodules, package.json, scripts/languageserver/buildscript.jl, scripts/languageserver/main.jl, scripts/terminalserver/terminalserver.jl, scripts/weave/run_weave.jl, src/extension.ts, src/packagepath.ts, src/repl.ts, src/smallcommands.ts, src/tasks.ts, src/weave.ts
A first step to get thing working on 1.0. 
Works off packages in the user's default package directory so will require:
- CSTParser v0.4.0
- Tokenize v0.5.2
- JSON
- DocumentFormat
- StaticLint v0.0.1
- Revise
We need to make a decision/work out how we're going to distribute the dependencies, I think my preferred approach would be a meta-package, `julia-vscode.jl` that includes the relevant versions which either the user would have to install or, ideally, we could install as part of the build process
=> J0.7/1.0 update

package.json, src/settings.ts
Makes things look nicer in the new settings editor.
=> Some small improvements to the settings

.gitmodules
We need this even before we merge #553.
=> Add submodule for SymbolServer

src/packagepath.ts
The existing version doesn't work if one doesn't have any packages deved.
=> Change how we find the pkg path

scripts/languageserver/main.jl, src/extension.ts, src/telemetry.ts
=> Fix crash reporting on Mac

src/repl.ts
Fixes indentation problems.
I have no idea how to test this. 
Ref: https://discourse.julialang.org/t/vs-code-extension-v0-11-0-beta-release/17541/9
=> use bracketed paste to send text to the terminal, fixes indentation problems

src/repl.ts
Use `include` where possible when running `.jl` files.
=> fix run file

scripts/languageserver/main.jl
=> Stop sending crash reports for wrong julia version

src/jlpkgenv.ts
=> Fix a julia environment selector UI bug

src/repl.ts
=> Make sure backslash in F5 runs are ok

package.json
This is a minor change to package.json suggested by Intellisense. Seems reasonable 😊 
I can add this to my other PR (#641) if you prefer.
=> Intellisense suggested changing Languages -> Progamming Languages

package.json, scripts/terminalserver/terminalserver.jl, src/repl.ts
=> add plotpane config option

README.md
As [suggested on Slack](https://julialang.slack.com/archives/C6LV2R5JB/p1551363495010400?thread_ts=1551363132.009800&cid=C6LV2R5JB), this is a stop-gap measure to make sure new users are aware of the limitation.
=> Add note about julia 1.1 compatibility to README

scripts/terminalserver/terminalserver.jl
Takes account of internal changes to Pkg between 1.? and 1.1.?
=> fix Pkg availability check (Revise)

syntaxes/julia.json
@haberdashPI do you want to take a quick look over this? I just copied the auto-converted stuff from atom-language-julia, it might be good if you could briefly check whether this is what you wanted.
=> Update grammar by copying from atom-language-julia

package.json, src/repl.ts
=> add delete all plots

src/tasks.ts
=> Have julia tasks use active julia env

src/weave.ts
=> Use WebView for weave

src/juliaexepath.ts
=> Resolve paths beginning with tilde as $HOME

src/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/702.
=> Fix JULIA_EDITOR path on mac

scripts/weave/preview.tpl
=> Make sure all background in weave preview is white

src/repl.ts
=> Fix executeCode for single line case

syntaxes/julia.json
Also, updated the syntax file from atom-language-julia.
=> Fixed greedy highlighting of embedded C++.

package.json, src/repl.ts
Addresses #560.
Possible TODOs:
~- Add more delimiters.~
~- Make delimiters configurable.~
=> Add cell-wise evaluation.

scripts/terminalserver/repl.jl, scripts/terminalserver/terminalserver.jl
=> Run code with proper location information

src/jlpkgenv.ts
=> Don't notify LS about initial env

package.json
This is a proposition to improve consistency and uniformity about the extension commands.
=> Improve Command Title

syntaxes/julia.json
Just copies over the latest changes from upstream.
=> Update julia.json from upstream

package-lock.json, package.json, src/extension.ts, src/juliaexepath.ts, src/telemetry.ts
Fixes #938.
~~Still needs more testing, I'm not sure whether it actually does send the information or not :)~~
Now tested that it works. Ready for review :)
=> Send Julia version in telemetry

package.json
I'm going to just merge this, it should be harmless.
=> Update two npm scripts

scripts/terminalserver/terminalserver.jl
Fixes #958. Hopefully ;) @jkrumbiegel would be great if you could test this once we ship the next beta release.
=> Run user code in latest world age

src/juliaexepath.ts
One more PR ;) I think with the recent CSTParser updates we are ready for 1.4?
=> Auto detect Julia 1.4

src/repl.ts
Handles changes here: https://github.com/julia-vscode/LanguageServer.jl/pull/509
=> Change to getCurrentBlock command args

scripts/terminalserver/terminalserver.jl
=> Fix a world age bug in the REPL display code

package.json
Turn this off by default for now
=> disable call lint

.gitignore, .vscodeignore, package-lock.json, package.json, src/scripts/updateDeps.ts
I'm going to merge this right away, it doesn't affect any runtime behavior.
=> Add updateDeps script

src/extension.ts, src/telemetry.ts
@ZacLN I'm going to merge this right away, I'm trying to get the insider channel to work, and this is all related to that. If you see any problems after the merge, please still flag :)
=> Make telemetry work in insider build

scripts/languageserver/packages/Manifest.toml, src/extension.ts, src/telemetry.ts
Goes with https://github.com/julia-vscode/SymbolServer.jl/pull/114.
=> Harden symserver against segfaults

src/repl.ts
=> Fix JULIA_EDITOR to work on remote environments

scripts/debugger/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1078.
=> Fix drilldown into structs when value undef

scripts/debugger/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1080.
=> Make sure include works during debug

src/smallcommands.ts
@tk3369 found this one, at some point we must have renamed the config setting.
=> Fix a wrong config name

src/extension.ts, src/telemetry.ts
This seems a bit more specific than what we had previously.
=> Make telemetry language more precise

src/scripts/updateDeps.ts
This is only for me and the release process.
=> Improve the deps update script

.vscode/launch.json, package.json, src/repl.ts, src/test/suite/utils.test.ts, src/utils.ts
=> Prioritize JULIA_NUM_THREADS if it exists

.gitignore, .vscode/launch.json, .vscodeignore, package-lock.json, package.json, webpack.config.js
Fixes https://github.com/julia-vscode/julia-vscode/issues/991.
I just followed the instructions at https://code.visualstudio.com/api/working-with-extensions/bundling-extension.
Main benefit is that the extension should load faster and it should also be quite a bit smaller when distributed.
=> Use webpack for the extension

package-lock.json, package.json, src/scripts/updateDeps.ts
Now also automatically downloads, converts and updates the grammar file from the upstream atom repo.
=> Improve deps update script

scripts/languageserver/main.jl
We can't get rid of those errors because of a race condition in the base Julia precompile, but this way at least they all are easily identified in crash reporting.
=> Use our own exception type for precompile failures

scripts/languageserver/main.jl
=> Fix a typo

package.json
=> update julia config options

package.json
=> Fix default value for "julia.useCustomSysimage".

src/repl.ts
=> Adopt VS Code's 'asWebviewUri' API

.vscode/settings.json
We have more than the default 10 :)
=> Increase git.detectSubmodulesLimit to 20

package.json, src/smallcommands.ts
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/700.
=> Remove Toggle File Linting

src/extension.ts, src/interactive/plots.ts, src/interactive/repl.ts, src/interactive/workspace.ts, src/juliaDebug.ts
This is only the reorg part of https://github.com/julia-vscode/julia-vscode/pull/1222. It doesn't (shouldn't) change any code whatsoever.
=> split repl.ts into multiple files

package.json, src/smallcommands.ts
This command is no longer handled on the LS side, and we are getting crash reports for users trying it.
=> Remove dead command

src/juliaexepath.ts
We always try to stay one step ahead of the official releases :)
=> Add Julia 1.4.3 to the list of versions

src/interactive/modules.ts, src/interactive/repl.ts
=> basic connection emission/listening

package.json, src/interactive/repl.ts
context: https://github.com/julia-vscode/julia-vscode/pull/1222#discussion_r431174770
=> unify code execution settings

CHANGELOG.md, src/interactive/repl.ts
=> improve cell delimiter regex

package.json
This PR adds a npm task for initializing a freshly cloned repo for local development (suggested in https://github.com/julia-vscode/julia-vscode/pull/1266#issuecomment-636986701)
=> Add npm task for installing all dependencies after a fresh clone

src/interactive/misc.ts, src/interactive/modules.ts, src/interactive/repl.ts
I don't think we need to define this ourselves, right?
=> Remove a duplicate def of TextDocumentPositionParams

package.json
Fixes https://github.com/julia-vscode/julia-vscode/issues/1277.
=> rm dead command

src/interactive/repl.ts, src/interactive/workspace.ts
- update workspace on REPL initialization
- remove duplicated tree updates
- rm dead setTerminal stuff
- concentrate logic into workspace.ts
fixes #1298
=> a bit more improvements on workspace:

scripts/terminalserver/repl.jl, scripts/terminalserver/terminalserver.jl
=> fix repl initialization

scripts/terminalserver/terminalserver.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1316.
Also prints useful parser errors now.
=> fix repl again

scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/terminalserver/terminalserver.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1323#issuecomment-641918928.
=> fix display order

package.json
Support for https://github.com/julia-vscode/DocumentFormat.jl/pull/104 and https://github.com/julia-vscode/LanguageServer.jl/pull/746
=> Update for DocumentFormat config changes

src/extension.ts
While I tackle #1183 , I found this error and so extract here.
Currently we set `g_languageClient` when it's fired up, rather than its's ready, which may result in more internal "language client ready yet" error.
commits:
- set `g_languageClient` object on LS "ready" rather than fire
- don't create global ls start up indicator
=> more careful LS startup:

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1339.
=> immediately move to next cell

scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/packages/VSCodeServer/src/repl_protocol.jl, src/interactive/repl.ts, src/interactive/workspace.ts
~~Still has a couple of TODOs, but this migrates things to the same message dispatching framework that we use in the LS and hopefully soon in the debugger as well.~~
Ok, ready for review, it should all work. This PR also adds crash reporting for the REPL process.
=> Use JSONRPC msg dispatcher for REPL

scripts/packages/VSCodeServer/src/request_handlers.jl
follows up #1368 , currently we lacks the names for toplevel module
=> fix WS regression for toplevel module

scripts/packages/DebugAdapter/Project.toml, scripts/packages/VSCodeDebugger/Project.toml
With this the F5 debugger _really_ gets precompiled.
=> Add two Project.toml files so that things precompile

src/interactive/results.ts
See https://github.com/julia-vscode/julia-vscode/issues/1377#issuecomment-647630203.
=> better inline result background color

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1394.
=> improve repl/LS startup error handling

azure-pipelines.yml, src/juliaexepath.ts
For now I just want to trigger a CI build that includes Julia 1.5 to see whether that works or not.
=> Add Julia 1.5 support

scripts/packages/VSCodeServer/src/repl_protocol.jl, scripts/packages/VSCodeServer/src/trees.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1402.
=> fix WS tableview

scripts/packages/VSCodeServer/src/eval.jl, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1373.
Also cleans up stacktraces shown in the REPL.
=> make sure to show errors when evaling file

scripts/packages/VSCodeServer/src/trees.jl
Alternative to https://github.com/julia-vscode/julia-vscode/pull/1388.
=> fix treeview world age problems again

src/interactive/misc.ts, src/interactive/modules.ts, src/interactive/repl.ts
Requires https://github.com/julia-vscode/LanguageServer.jl/pull/778.
Should fix a few of the errors in the crash reports.
=> check docversion in module/blockrange requests

scripts/packages/VSCodeServer/src/eval.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1428.
=> fix display_error(stderr, err, nothing) call

src/debugger/debugProtocol.ts, src/debugger/juliaDebug.ts
Requires https://github.com/julia-vscode/DebugAdapter.jl/pull/7.
[This diff](https://github.com/julia-vscode/julia-vscode/pull/1432/files?diff=split&w=1) hides the whitespace changes.
Printing could be prettier, but that's probably not that big of a concern right now.
=> stepInTargets support

scripts/packages/VSCodeServer/src/eval.jl
Actually fixes https://github.com/julia-vscode/julia-vscode/issues/1428 now -- turns out I didn't test this very well...
=> re-fix display_error bug

src/extension.ts, src/interactive/modules.ts, src/telemetry.ts
Fixes https://github.com/julia-vscode/julia-vscode/pull/1423#issuecomment-651915275.
=> more and improved error tracing

src/tasks.ts, src/utils.ts
Gets us closer to #1401. Also simplified the whole tasks code, no need for all the manual promise stuff there.
=> Some strict improvements

scripts/packages/VSCodeServer/src/trees.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1439.
=> fix undef handling in workspace

package.json
Fixes https://github.com/julia-vscode/julia-vscode/issues/1381.
=> stop using Ctrl+J prefix

package.json
corresponds to https://github.com/julia-vscode/LanguageServer.jl/pull/792
=> add disabledDirs config

package.json, src/interactive/documentation.ts
it seems like I somehow reverted the merge commit
=> re: doc simplifications

azure-pipelines.yml, scripts/testenvironments/chromeprofileformat/Manifest.toml, scripts/testenvironments/chromeprofileformat/Project.toml, src/scripts/updateDeps.ts
This doesn't touch any file that is actually shipped with the extension, so hopefully safe.
=> Add ChromeProfileFormat to updateDeps.ts and CI

scripts/packages/VSCodeServer/src/repl.jl
Should fix https://github.com/julia-vscode/julia-vscode/issues/1447 and (maybe) https://github.com/julia-vscode/crashreporting-issues/issues/5.
=> more isrepl checks

scripts/packages/VSCodeServer/src/eval.jl
Fixes a bug from crash reporting.
=> Fix a world age error and handle faulty show methods

scripts/packages/VSCodeServer/src/trees.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1491.
=> hide internal errors in WS

azure-pipelines.yml
Fixes https://github.com/julia-vscode/julia-vscode/issues/1436.
=> Publish to openvsx

azure-pipelines.yml
Turns out this is easier with less stages.
=> Tweak pipeline definition

scripts/terminalserver/terminalserver.jl
=> new way to load Revise

src/juliaexepath.ts
see https://github.com/JuliaLang/julia/pull/35059.
=> Julia 1.5 has changed default path

src/extension.ts
Crashes in `activate` are especially bad because then large parts of the extension aren't loaded properly.
This is the minimal code to add crash reporting for `activate`, so that we can learn what is going wrong.
The diff here looks horrible, but if you ignore whitespace differences it is a very minimal change.
=> Add crash reporting to activate function

src/interactive/modules.ts
- don't try to send request when ls/repl connection haven't been established
- enable telemetry correctly for any consumer functions of them
Currently these code spams the console with error logs (when `g_launguageClient` or `g_connection` isn't established, especially on startup) and this PR should suppress them.
Obviously this won't fix our recent `get_offset` errors though.
=> fix up connection/module handling:

src/interactive/repl.ts
closes https://github.com/julia-vscode/julia-vscode/issues/1566
=> supports "#%%" and "# %%" cell separators

scripts/packages/VSCodeServer/src/display.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1573.
=> invokelatest in showingrid_notification

src/juliaexepath.ts
We should try to ship this quickly, given that 1.5.1 was just released.
=> Add Julia 1.5.1 & 1.5.2 and remove 1.4.3

package.json
Fixes https://github.com/julia-vscode/julia-vscode/issues/1713.
=> julia.NumThreads: machine-overrideable

package.json, src/extension.ts
fixes https://github.com/julia-vscode/LanguageServer.jl/issues/841
requires https://github.com/julia-vscode/LanguageServer.jl/pull/842
@pfitzseb @davidanthoff please feel free to change the behavior by pushing into this branch; I've been a bit off from the code base and this approach may contain something that should be fixed.
/cc @zerefwayne ask me any question on those code anyway :)
=> provide ways to refresh LS

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1730.
=> remove results when process exits

package.json, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1739.
=> pass Ctrl-C to REPL when not evaling

package.json, scripts/environments/development/Manifest.toml, scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/packages/VSCodeServer/src/misc.jl, scripts/packages/VSCodeServer/src/repl_protocol.jl, src/interactive/repl.ts
This is especially useful when invoked from active editor, etc.
=> add 'Activate Parent Environment' command

scripts/packages/VSCodeServer/src/display.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1748.
=> fix typo in tableviewer code

src/juliaexepath.ts
Prepare for a potential 1.5.4 release, we're always trying to be one step ahead with this :)
=> Add support for Julia 1.5.4

src/extension.ts, src/jlpkgenv.ts
Not sure if we want this, but it's very convenient to also watch the global environment for changes and re-index if necessary.
=> better env watching

scripts/packages/VSCodeServer/src/display.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1795.
=> fix inline plot display with plotpane disabled

src/interactive/results.ts
and don't display them when linenumber == 0
=> validate stacktrace highlights

scripts/packages/VSCodeServer/src/debugger.jl, src/debugger/debugProtocol.ts, src/debugger/juliaDebug.ts, src/interactive/repl.ts
and fix source_path.
Needs https://github.com/julia-vscode/DebugAdapter.jl/pull/25.
=> more robust attached debugger

README.md
- update link in doc section to julia-vscode.org
- add a sentence about legacy docs in the wiki
=> Update README doc link to stable docs

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1765.
=> only move cursor after eval if cursor hasn't been moved

scripts/packages/VSCodeServer/src/progress.jl
Requires https://github.com/julia-vscode/JSONRPC.jl/pull/40.
Fixes https://github.com/julia-vscode/julia-vscode/issues/1769.
Closes #1772
=> flush progress messages

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1761.
=> send SIGINT if more than 3 interrupts in 1s

azure-pipelines.yml
They changed the publishing process, so right now it is broken. For now I am disabling, until I have time to fix it properly.
=> Disable ovsx publishing for now

scripts/packages/VSCodeServer/src/repl.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1837.
=> fix backtraces in REPL

scripts/languageserver/main.jl
I'm going to merge this right away, just wanted to make sure everyone saw this. I think this is all we have to do for this, right?
=> Update symbol store format version to v3

package.json, scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/packages/VSCodeServer/src/display.jl, scripts/packages/VSCodeServer/src/eval.jl, scripts/packages/VSCodeServer/src/repl.jl, scripts/packages/VSCodeServer/src/repl_protocol.jl, scripts/terminalserver/terminalserver.jl, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1845.
=> add setting to disable progress logging

src/interactive/repl.ts
=> show remaining time for progress bars

azure-pipelines.yml, src/juliaexepath.ts
=> Add support for Julia 1.6

CHANGELOG.md, src/interactive/plots.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1937.
=> fix svg display regression

scripts/packages/VSCodeServer/src/eval.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1940.
Not sure whether we should merge this or not, since technically it's not a bug in our code. AFAICT it won't hurt either though.
=> wrap out-channel content

scripts/packages/VSCodeServer/src/repl.jl
=> use repl ast transforms on 1.5 and up

scripts/packages/VSCodeServer/src/repl.jl
Fixes a bug that got reported on Slack.
Turns out the repl backend isn't guaranteed to be set up in an `atreplinit` block, so let's do the same as Revise to hook it.
=> more robust repl hook setup

src/docbrowser/documentation.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1956.
=> fix search zindex in docpane

scripts/packages/VSCodeServer/src/repl.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1972.
=> fix typo in repl init code

src/debugger/debugFeature.ts, src/docbrowser/documentation.ts, src/extension.ts, src/interactive/modules.ts, src/interactive/plots.ts, src/interactive/repl.ts, src/interactive/results.ts, src/interactive/workspace.ts, src/jlpkgenv.ts, src/openpackagedirectory.ts, src/packagedevtools.ts, src/smallcommands.ts, src/utils.ts, src/weave.ts
More generic alternative to https://github.com/julia-vscode/julia-vscode/pull/1982.
=> Command middleware

scripts/packages/VSCodeServer/src/misc.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1977.
=> hide prompt for activate command

src/interactive/repl.ts, src/telemetry.ts, src/utils.ts
Might fix https://github.com/julia-vscode/julia-vscode/issues/1978. I don't think this will break anything, so might make sense to get in regardless.
=> unique pipe names

package.json
Fixes #2026
- [n/a] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
Does this change require an entry in the change log? Most of the changes related to Notebooks is a single feature, not sure we want separate change log entries for each, i'd assume when this is released we have a single entry saying `new feature xyz`
=> Activate extension when opening an ipynb notebook

src/notebook/helpers.ts, src/notebook/notebookKernel.ts
@davidanthoff 
Not sure I need an issue when submitting changes to the feature branch.
Same with updates to the change log.
Let me know if these are required.
=> Ensure we perform updates to Document sequentially

src/notebook/notebookKernel.ts
I think i added a bug, during a merge issue.
The output is getting cleared
still trying to test this, things are a little slow to start (starting julia everytime is a little slow)
=> Fix clearing output

package.json
=> Change executablePath scope to machine

src/juliaexepath.ts
Just want to be ready for it :)
=> Add support for Julia 1.6.1

src/juliaexepath.ts
They changed the install location AGAIN...
=> Fix Julia 1.6 paths on Windows

scripts/weave/run_weave.jl, src/weave.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2129.
=> weave in current env

scripts/terminalserver/terminalserver.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1659.
=> fix code loading with Distributed

src/debugger/juliaDebug.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/1640.
=> no-debug terminal name change to "Julia Session"

scripts/languageserver/main.jl
My understanding is that we need this for https://github.com/julia-vscode/SymbolServer.jl/pull/213, right @ZacLN?
=> Update symbol store version to v5

scripts/error_handler.jl, scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/packages/VSCodeServer/src/repl.jl, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2173.
I *think* our connection handling is fairly correct with this.
=> fix tmux issues

CHANGELOG.md, scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/packages/VSCodeServer/src/repl.jl, src/interactive/repl.ts
=> improvements to tmux/external process workflow

src/interactive/repl.ts
=> tilde-expansion in special julia links

src/scripts/updateDeps.ts
I'm going to merge right away, given that I'm the only one using this in any case. Just wanted to show off how cool `juliaup` is ;)
=> Use juliaup in updateDeps.ts

package.json, src/interactive/plots.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2220.
=> Plot navigator robustness

src/debugger/debugFeature.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2219.
=> fix compiled mode/fns when f5-debugging

webpack.config.js
=> Fix some small probles in webpack.config.js

src/juliaexepath.ts
Some this regression crept into the recent notebook PR.
=> Fix Windows search paths

src/notebook/notebookKernel.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2244.
This now uses a Julia env if it is in the folder of the notebook, or a parent if that is still in the workspace.
=> Detect notebook Julia environments

src/notebook/notebookFeature.ts
=> Support for preferred kernels

src/notebook/notebookFeature.ts
Fixes #2238.
@DonJayamanne, does this look ok to you? It feels a bit ad-hoc, but I guess this is how we would do this kind of thing?
=> Reuse kernel even if notebook was closed

scripts/packages/VSCodeServer/src/notebookdisplay.jl, src/notebook/notebookKernel.ts
Just avoid some code duplication and make it easier to add more MIME types. Also use the limit function to generate messages.
=> Rework notebook display

package.json
Requires https://github.com/julia-vscode/DebugAdapter.jl/pull/41.
=> interpret Broadcast while debugging

src/notebook/notebookFeature.ts
=> Use a more standard name for kernel

package.json, scripts/languageserver/main.jl, src/extension.ts
Requires https://github.com/julia-vscode/LanguageServer.jl/pull/966.
=> make cache download configurable

scripts/packages/VSCodeServer/src/serve_notebook.jl, src/notebook/notebookKernel.ts
`include` did not work at all without this :)
=> Properly set paths for notebook execution

src/notebook/notebookFeature.ts
=> Fix notebook restart

scripts/packages/VSCodeServer/src/serve_notebook.jl
=> Send crash reports when notebook kernel crashes

scripts/packages/VSCodeServer/src/serve_notebook.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2320.
=> use softscope transform for notebook eval if available

scripts/packages/VSCodeServer/src/eval.jl, scripts/packages/VSCodeServer/src/misc.jl, scripts/packages/VSCodeServer/src/serve_notebook.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2333
=> Revise.revise for notebook eval

.vscodeignore
=> Remove some unneeded files from package

src/extension.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2353.
=> fix open settings button

src/extension.ts, src/jlpkgenv.ts, src/juliaexepath.ts, src/utils.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2363.
I can't test this right now because I _also _broke my `juliaup` at the same time, so nothing is working here... If someone else could check this branch, please do!
=> Fix Julia exe search

src/interactive/plots.ts
=> Fix image-like size to always fit pane

src/interactive/workspace.ts
when Julia REPL dies.
Fixes [these pesky `Connection got disposed` errors](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%252FresourceGroups%252FDefault%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fjulia-vscode%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22b08cffd1-0abd-11ec-a602-8b5497aa9e17%22%2C%22timestamp%22%3A%222021-09-01T00%3A43%3A56.381Z%22%2C%22cacheId%22%3A%22e44585a7-2801-439b-8bb8-2f3205acf50c%22% …
=> Dispose REPLNode in workspace

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/pull/2329#discussion_r683629852
=> improve displayDiagnostics

package.json, src/interactive/repl.ts
and doesn't read from FS
Fixes https://github.com/julia-vscode/julia-vscode/pull/1728#issuecomment-913544737.
=> executeActiveFile runs editor content

src/jlpkgenv.ts
Fixes the useless error message in #2438.
=> Fix jlpkgenv error message printing

scripts/notebook/notebook.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2453.
=> load InteractiveUtils in notebooks

scripts/plots/main_plot_webview.js, src/interactive/plots.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2449.
Not sure if this is great, but it certainly doesn't feel bad. Needs docs though, I guess.
=> restrict plot pan/zoom to alt/option key

scripts/packages/VSCodeServer/src/serve_notebook.jl, src/notebook/notebookKernel.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2326
=> Include error message in stack trace

package.json, src/extension.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2274.
=> Hide contributed views until extension is activated

package.json, src/interactive/repl.ts
Adds a `Julia: Disconnect external REPL` command and improves the behavior of `Julia: Stop REPL` for persistent sessions.
=> improve tmux session handling

scripts/packages/VSCodeServer/src/VSCodeServer.jl, scripts/packages/VSCodeServer/src/display.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1809.
=> add at-vscodedisplay for tables

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2510.
=> set env vars inside of tmux

CHANGELOG.md, package.json, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2566.
=> Configurable cell delimiters

.vscode/launch.json
=> Update Run LS script with symbolcache_upstream arg

CHANGELOG.md, scripts/tasks/task_compileenv.jl
=> Support newer manifest versions

src/juliaexepath.ts
=> Update the Julia versions we search for

src/juliaexepath.ts
I think 1.7.1 is going to be released any moment, and with 1.7.2 added as well we're then one step ahead, as we normally try to be.
=> Add Julia 1.7.1 and 1.7.2

src/juliaexepath.ts
=> Give config setting priority over juliaup

CHANGELOG.md, src/interactive/plots.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2651.
=> Fix plotpane issues

src/extension.ts
=> improve output channel command registration

src/interactive/plots.ts
Fixes #2672. Hopefully for real this time.
=> Fix plot pane focus/location issues again

scripts/packages/VSCodeServer/src/eval.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2715.
=> Fix code block syntax for inline hovers

CONTRIBUTING.md
add instructions to contribution guide
=> add instructions

package.json
=> Add Send current line of selection to REPL to context menu

scripts/packages/VSCodeServer/src/trees.jl
=> Improve enum rendering

package.json, scripts/notebook/notebook.jl, scripts/packages/VSCodeServer/src/serve_notebook.jl, src/interactive/workspace.ts, src/notebook/notebookFeature.ts, src/notebook/notebookKernel.ts
- removes `restartKernel`/`stopKernel` commands from command palette
- adds Restart/Stop buttons to notebook interface
- adds interrupt handler
- fixes notebook restart behaviour
=> Various notebook fixes

src/notebook/notebookKernel.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2737.
=> Respect thread setting for notebook kernels

package.json, scripts/packages/VSCodeServer/src/eval.jl, src/interactive/workspace.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2554.
=> Various eval fixes

scripts/packages/VSCodeServer/src/eval.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2652.
=> Show inline error even with semicolon

scripts/packages/VSCodeServer/src/tables/tableviewer.jl, src/interactive/tables.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2591.
=> Show Julia type in table header tooltip

scripts/packages/VSCodeServer/src/eval.jl, scripts/packages/VSCodeServer/src/repl.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2753.
=> Fix LoadError unwrapping in REPL

package.json, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2756.
=> Add "Always copy" option to "Connect to external REPL"

src/interactive/repl.ts
to avoid reconnection issue with VS Code's persistent terminal feature
Fixes https://github.com/julia-vscode/julia-vscode/issues/2621.
=> Mark Julia REPL as transient

scripts/packages/VSCodeServer/src/serve_notebook.jl
Right now notebook kernel crashes if the display method of any value we try to show has an error. This properly catches these errors.
=> Catch display errors in notebook exec

scripts/packages/VSCodeServer/src/misc.jl
=> Fix a world age bug in revise() call

scripts/packages/VSCodeServer/src/serve_notebook.jl
Now make sure we don't crash inside the crash handlers :)
=> Make error handling in notebooks more robust

scripts/packages/VSCodeServer/src/display.jl, scripts/packages/VSCodeServer/src/repl.jl
Alternative to https://github.com/julia-vscode/julia-vscode/pull/2793. 
Fixes https://github.com/julia-vscode/julia-vscode/issues/2484.
=> Display diagnostics in REPL

scripts/notebook/notebook.jl, scripts/packages/VSCodeServer/src/serve_notebook.jl
Hopefully this will allow us to figure out what is going on with https://discourse.julialang.org/t/notebook-cells-hung-up-in-vs-code/78492.
=> Add more startupt output to notebook server

src/interactive/repl.ts
I think this should all help with various crash reports we have.
=> Fix various REPL bugs

scripts/packages/VSCodeServer/src/serve_notebook.jl
Fixes a bug from crash reporting
=> Fix a bug in notebook error handling

scripts/packages/VSCodeServer/src/profiler.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2808.
=> Show warning for empty profile traces

scripts/notebook/notebook.jl
@pfitzseb I'm merging right away, hopefully this can help us narrow down the notebook issue we saw on discourse.
=> Add more notebook diagnostics

src/telemetry.ts
Fixes one small bug, and migrates to connection strings, as the old way of connecting is being deprecated by MS.
=> Telemetry improvements

package.json
At least https://code.visualstudio.com/api/references/activation-events#workspaceContains seems to indicate that this should work.
=> Use glob pattern for workspaceContains activation

src/tasks.ts
This has annoyed me for a long time, makes the UI a bit more consistent with other tasks.
=> Capitalize task source properly

src/notebook/notebookKernel.ts
This might fix the bug we've been discussing on discourse.
=> Fix a notebook bug

src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2849.
=> Show Julia version in REPL title

scripts/packages/VSCodeServer/src/eval.jl
Will hopefully help debugging https://github.com/julia-vscode/julia-vscode/issues/2802.
=> Speculative fixes for repl_runcode_request

scripts/terminalserver/terminalserver.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1659.
=> Fix distributed VSCodeServer loading

package.json, src/interactive/profiler.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2789.
=> Save Profile to File command

scripts/packages/VSCodeServer/src/serve_notebook.jl, src/interactive/plots.ts, src/interactive/tables.ts, src/interactive/workspace.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2843.
=> Fix lazy table display for notebooks

package.json
=> change activation on jl to on Project.toml

scripts/packages/VSCodeServer/src/progress.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2853.
=> Lock progress-notification

src/extension.ts
and re-use all LS output channels
=> Fix LS restart logic

scripts/packages/VSCodeServer/src/eval.jl
Might fix https://github.com/julia-vscode/julia-vscode/issues/2861.
=> Fix global ans assignment logic

libs/documenter/documenter-vscode.css, libs/documenter/documenter-vscode.scss, libs/plotter/plotter.css, libs/plotter/plotter.scss, src/docbrowser/documentation.ts, src/interactive/plots.ts
Helps with https://github.com/julia-vscode/julia-vscode/issues/2868.
=> Improve docs css

package.json
Fixes https://github.com/julia-vscode/julia-vscode/pull/1509#issuecomment-1114635040.
=> Integrate with file/newFile

src/extension.ts, webpack.config.js
We lost that check in one of the path finding rewrites.
=> Re-add check for valid Julia path

scripts/packages/VSCodeServer/src/eval.jl
=> Use markdown show method for inline display popup

README.md
=> Add direct VS Code link to extension

scripts/packages/VSCodeServer/src/eval.jl, scripts/packages/VSCodeServer/src/repl.jl, scripts/terminalserver/terminalserver.jl, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2878.
Todo:
=> VS Code shell integration

src/debugger/juliaDebug.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2965.
=> Fix "Run in new REPL"

package.json, src/debugger/debugConfig.ts, src/interactive/plots.ts, src/interactive/profiler.ts, src/interactive/repl.ts, src/interactive/results.ts, src/utils.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/2970.
=> Consistent context key logic and naming in when clauses

src/extension.ts, src/interactive/repl.ts
since it's ok for the LC to not be initialized when using it.
=> setLanguageClient before it's fully initialized

.github/workflows/main.yml, scripts/languageserver/main.jl, scripts/packagedev/tagnewpackageversion.jl, scripts/tasks/task_compileenv.jl, src/extension.ts, src/packagedevtools.ts, src/scripts/juliaprojectcreatescripts/create_ls_project.jl, src/scripts/juliaprojectcreatescripts/create_pkgdev_project.jl, src/scripts/juliaprojectcreatescripts/create_sysimagecompile_project.jl, src/scripts/juliaprojectcreatescripts/create_test_debugadapter_project.jl, src/scripts/juliaprojectcreatescripts/create_test_vscodedebugger_project.jl, src/scripts/juliaprojectcreatescripts/create_test_vscodeserver_project.jl, src/scripts/updateDeps.ts, src/tasks.ts
Ideally we would merge this by first running the old update script on `master`, then merge this one here and then run this new update script.
=> Use one Julia project per Julia minor version

scripts/packages/VSCodeServer/src/eval.jl
when show_code==true.
Fixes https://discourse.julialang.org/t/suddenly-repl-in-vscode-becomes-weird/85459.
=> Fix shell integration code for inline eval

package.json
Fixes https://github.com/julia-vscode/julia-vscode/issues/2997.
=> Hide New Julia File menu entry when extension not active

src/juliaexepath.ts
=> Search for Julia 1.8.1 and remove 1.7.4

package.json
Probably fixes https://github.com/julia-vscode/julia-vscode/issues/3009.
=> Adjust scopes for various persistent session related settings

src/testing/testFeature.ts
=> Add more startup flags for test process

scripts/testserver/testserver_main.jl, src/extension.ts, src/testing/testFeature.ts
=> Add more error handling for testing feature

src/testing/testFeature.ts
Fixes https://github.com/julia-vscode/TestItemRunner.jl/issues/19.
=> Use shell with spawn on non Win platforms for test process

src/extension.ts, src/globalDiagnosticOutput.ts, src/juliaexepath.ts
For now it provides some info about identified Julia versions. I hope this can help get to the root issue with the test process launch.
=> Add a global extension output channel for diags

src/juliaexepath.ts
=> Add more diagnostic output

src/testing/testFeature.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3055.
=> Handle an error condition in testing

scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl
=> Handle more errors during testing

src/testing/testFeature.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3045.
=> Use the NumThreads setting for test processes

src/juliaexepath.ts
=> Fix a diagnostic output bug

src/testing/testFeature.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3057.
=> Add cancel support to testing

scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl
Fixes https://github.com/julia-vscode/TestItemRunner.jl/issues/26.
=> Put error message formatting behind invoke and try catch

scripts/packages/VSCodeServer/src/profiler.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3092.
=> fix: use correct label for alloc profiler

src/interactive/repl.ts
if text in result range changes while evaluating
Fixes https://github.com/julia-vscode/julia-vscode/issues/3105.
=> fix: stop creating orphaned results

src/testing/testFeature.ts
This fixes a bug from crash reporting. I'm going to merge this without review, given that the test feature is technically in preview in any case.
=> Fix a bug in the publishTestsHandler

scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl
=> Add some diagnostic output for the test item runner

scripts/packages/VSCodeServer/src/display.jl, scripts/packages/VSCodeServer/src/notebookdisplay.jl, src/interactive/plots.ts
=> Add support for vega-lite 5

package.json
Fixes https://github.com/julia-vscode/julia-vscode/issues/3234.
=> fix: use correct condition for compiled mode UI

src/juliaexepath.ts
=> Add Julia 1.9.2 and 1.9.3 on Windows

.github/workflows/main.yml
=> Run tests on Julia 1.9

src/interactive/profiler.ts
before sending a trace to it.
Fixes https://github.com/julia-vscode/julia-vscode/issues/3316.
=> fix(profiler): await JS loaded in profiler webview

src/notebook/notebookFeature.ts
=> Support raw notebook cells

scripts/packages/VSCodeTestServer/src/VSCodeTestServer.jl, scripts/packages/VSCodeTestServer/src/testserver_protocol.jl, src/testing/testFeature.ts
=> if string comparison in @test fails, show as diff

syntaxes/julia_vscode.json
=> Fix typo in julia_vscode.json

scripts/packages/VSCodeServer/src/progress.jl
This allows writing stuff like
```julia
with_logger(VSCodeLogger(ConsoleLogger(Debug))) do
@debug "hello world"
@logmsg LogLevel(-1) "Progress" progress=0.5
end
```
Untested for now, just firing off a quick suggestion from the web
=> Allow setting parent logger in VSCodeLogger

CHANGELOG.md, src/jlpkgenv.ts, src/juliaexepath.ts, src/packagepath.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3446.
=> fix: user proper env while finding exe

scripts/packages/VSCodeServer/src/display.jl
Fixes https://github.com/JuliaDebug/Cthulhu.jl/issues/517
=> Fix displaying of inlay hints when plot pane disabled

CHANGELOG.md, package.json, src/interactive/repl.ts, src/utils.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3461.
Fixes https://github.com/julia-vscode/julia-vscode/issues/3061.
Supersedes https://github.com/julia-vscode/julia-vscode/pull/3291.
Kinda fixes https://github.com/julia-vscode/julia-vscode/issues/3342.
=> fix: improve tmux variable handling and quoting

CHANGELOG.md, package.json
Should this be machine-overridable instead?
=> machine-overridable of closeStrategy

CHANGELOG.md, src/interactive/repl.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3498.
=> fix: use external repl for code exec

.github/workflows/main.yml
=> Use newer versions of some github actions

CHANGELOG.md, scripts/packages/VSCodeServer/src/tables/tableviewer.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3545.
=> fix: only require pkg if not loaded in package_callbacks

CHANGELOG.md, src/debugger/debugConfig.ts, src/extension.ts, src/interactive/plots.ts, src/interactive/repl.ts, src/interactive/workspace.ts, src/smallcommands.ts, src/telemetry.ts
Fixes https://github.com/julia-vscode/julia-vscode/issues/3262, hopefully.
=> fix: set "always copy" in global config

CHANGELOG.md, src/notebook/notebookKernel.ts
=> Handle \r in outputs

CHANGELOG.md, scripts/packages/VSCodeServer/src/eval.jl, scripts/packages/VSCodeServer/src/repl.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3588.
=> fix: better LoadError unwrap logic

CHANGELOG.md, scripts/packages/VSCodeServer/src/eval.jl, scripts/packages/VSCodeServer/src/misc.jl, scripts/packages/VSCodeServer/src/repl_protocol.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3587.
=> fix: better stacktrace pruning

.github/workflows/main.yml, src/juliaexepath.ts
=> Support more Julia versions

scripts/languageserver/main.jl, src/extension.ts
=> Use a different Julia version for LS and SSP

src/juliaexepath.ts
Always trying to be one step ahead.
=> Add Julia 1.10.5 to search

scripts/terminalserver/terminalserver.jl
=> Load error handler into terminal process

src/testing/testFeature.ts
=> Don't run excluded test items

src/scripts/updateDeps.ts
=> Outdated-marking

src/testing/testFeature.ts
=> Fix a coverage line number bug

CHANGELOG.md, scripts/terminalserver/terminalserver.jl, src/interactive/repl.ts
May fix https://github.com/julia-vscode/julia-vscode/issues/3662.
=> fix: improve env handling at REPL startup

src/extension.ts, src/telemetry.ts
Requires https://github.com/julia-vscode/LanguageServer.jl/pull/1317
=> Send LS request timing telemetry in debug and prerelease version

CHANGELOG.md, package.json, src/debugger/debugFeature.ts
=> Add juliaAdditionalArgs to launch configuration

CHANGELOG.md, src/extension.ts
Fixes #3694, alternative to https://github.com/julia-vscode/LanguageServer.jl/pull/1322.
@ianfiske, I think this fix here tackles the root cause of the bug you reported. Could you try whether this one here also fixes the problem for you? Thanks!
=> Only send supported scheme project files to LS

.github/workflows/main.yml, .gitmodules, src/extension.ts, src/scripts/juliaprojectcreatescripts/create_ls_project.jl, src/scripts/updateDeps.ts
=> Drop pre Julia 1.10 support for the language server

package.json, src/tasks.ts
=> Remove live test setting that was never implemented

src/extension.ts, src/interactive/modules.ts
Hopefully fixes a crash report.
Also, I removed the loop. I think with the various `if` and `return` statements it could actually never loop in any case. Plus, not clear why we would want to loop in the first place :)
=> Fix-get-moduleAt

CHANGELOG.md, src/debugger/debugFeature.ts, src/interactive/repl.ts, src/notebook/notebookKernel.ts, src/tasks.ts, src/test/suite/utils.test.ts, src/testing/testFeature.ts, src/utils.ts
Fixes #3798 
- [N/A] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
=> Avoid setting JULIA_NUM_THREADS to empty string
