julia-vscode/julia-vscode

.gitignore
.vscodeignore
package.json
scripts/lintserver/lintserver.jl
src/async.ts
src/extension.ts
src/linter.ts

This uses Lint.jl to provide linting.
Things still to fix:

WIP: Linter

---

scripts/languageserver/provider_signatures.jl
scripts/languageserver/utilities.jl

fixes signatures and I uncovered a bug in get_word that caused hovers to crash when hovering brackets and other special characters

signatures run through arguments and don't crash

---

scripts/languageserver/languageserver.jl
scripts/languageserver/utilities.jl

Creates a cache of 100 documentation items.
Accessing hovers/completions on random areas of a .jl file in base this gives a ~x10 speed increase on the server side.
When the `Dict` exceeds 100 items 10 at random (ish) are deleted. We could rank how frequently each item is used and delete based on that but it doesn't seem worth it.

store cache of generated symbol documents 

---

src/extension.ts

@ZacLN Could you try this on your system? The general idea is that you can send a line of code from the editor to the REPL via Ctrl+Enter. This PR here should make sure that this works even if you haven't started the julia REPL before you send the first bit of code to the REPL.

Wait until REPL is started in send code command

---

scripts/languageserver/parse.jl

I believe we are linting everything twice right now, so disabling the unused lint pass for now to save some compute time.

Disable linting everything twice

---

scripts/languageserver/main.jl
scripts/languageserver/transport.jl
src/extension.ts

This should hide the raw JSON traffic if the extension is not running under the debugger.

Add debug mode option to language server

---

scripts/languageserver/provider_misc.jl

move `parseblocks(.)` from `parse_params` to `process`

move parseblocks to correct function

---

scripts/languageserver/parse.jl
scripts/languageserver/protocol.jl
scripts/languageserver/provider_misc.jl
scripts/languageserver/utilities.jl

This is ... slightly dodgy but I offer it as a suggestion for fixing the linting issue.
Maybe the lesser of two evils (the other being the `eval` of modified Range type definition).

Rename Range fieldname

---

scripts/languageserver/main.jl
scripts/languageserver/utilities.jl

I started to have a look at forking JuliaParser to have it store state and line/column info at intermediate stages of parsing and think it can be done but for now we may as well strip these dependencies?
I've also fixed `get_word` to handle cases such as `321sin(x)`.

remove JuliaParser dependency

---

package.json
src/extension.ts

@ZacLN  Can you try this? I hope this works on all systems now. I've removed the julia version selector, instead this should just show all the packages that are relevant for julia binary that is configured.

Fix open package command

---

scripts/terminalserver/terminalserver.jl
src/extension.ts

For the 0.5.0 release, just not run the terminal server socket, given that we don't use it in any case. This fixes #76.

Disable terminal server

---

julia.configuration.json

It is a bit annoying it auto closes `"` at the end of a string.
I see the official language uses this trick
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages
`{ "open": "'", "close": "'", "notIn": ["string", "comment"] },`

Disable autoClosingParis "" in string & comment

---

README.md

When setting ``julia.executablePath`` on Mac, users may be confused as to which of the many executables in the ``julia-x.x.app`` directory they should use. This note should resolve that confusion.

Updated README with note on Mac installation

---

package.json
src/extension.ts

Adds ability to turn linter on/off. Files must be saved to update (e.g. either add or remove linter messages)

make linter optional

---

package.json
src/extension.ts

This adds a weave command for [Weave.jl](https://github.com/mpastell/Weave.jl).
~~Right now I only support script weave files. It would be nice to add support for jmd files down the road, but I think before we do that we would need to figure out things like syntax highlighting and how that integrates with our LS etc.~~
FYI @mpastell

Add weave command

---

package.json
scripts/weave/preview.tpl
scripts/weave/run_weave.jl
src/extension.ts

Lots of stuff here:
- At every weave, pre-start a julia process for the next weave. This speeds things up quit a bit.
- Have two weave preview commands, one for column one, one for side-by-side.
- Add a save to file command that shows all the supported output formats as an option and then saves the result to a file.
- Weave preview works without saving the source file and no longer generates any files in the workspace.
- Generally suppress some annoying console output messages about Weave overriding various methods.
- Use a template for the preview that doesn't show a link to the source file, and open the weave homepage in a different window.
- Drop support for script input files, so only .jmd files are supported going forward.
I think that pretty much covers what we need for now.
FYI …

Various weave features

---

.gitmodules
.vscodeignore
scripts/languageserver/main.jl

This enables us to have only one copy of the packages that we need in the VS Extension, not one copy per julia version. I've also updated the versions of the packages that we use. I think it might be easiest to just merge this, and if there is still a problem, fix this on ``master``, because this is a bit annoying to do on a branch.

Simplify pkg handling

---

scripts/languageserver/main.jl

This changes things so that the VS Code extension now always uses LanguageServer etc. from the submodule in the VS Code extension, and never from the global .julia folder. Now that we only have one copy of the packages in the VS Code extension (no longer two for each version of julia), this seems fairly simple. Essentially the workflow now is that if you want to change something in say LanguageServer, you just make the change in the submodule.

Always load packages from extension

---

src/extension.ts

This copies the indentation rule from [here](https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/settings/language-julia.cson).
With current VS Code versions things should now unindent if you press Enter after the ``end``. Still not ideal, but I think we have to wait until Microsoft/vscode#2272 gets properly fixed for unindent when the word ``end`` is just typed.
This makes some progress on #37.

Update indentation rules

---

syntaxes/julia.json

Should the deprecated syntax be removed?
0.6:
- `typealias`
- `abstract`
- `bitstype`
1.0+:
- `type`
- `immutable`

Add v0.6 keywords to syntax highlighting

---

package.json
src/extension.ts

Add menu option to force reload of (edited) modules imported in user code. 
This may allow slightly faster editting of LanguageServer as long as the LanguageServerInstance struct isn't changed? 
Goes w/ https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/124

add reload-modules command

---

package.json
src/extension.ts

This uses the VS Code task system for running a) tests, b) build.jl and c) benchmarks.
Also removes the previous manual test runner stuff.

Use VS Code task system

---

package.json
src/extension.ts

Adds toggle lint for files/folders to the explorer menu. I'm not sure how we want to enable this persistantly, could we possibly use .vscodeignore ?

add toggle lint menu option

---

package.json
scripts/terminalserver/terminalserver.jl
src/extension.ts
src/repl.ts
src/weave.ts

Creates classes for weave/repl functionality so that they can be moved into seperate files.
I don't know much about typescript/OOP design so a quick review over the style is probably prudent.
I've added some infrastructure to have a REPL variables tree view but can't quite work out how to get the tree to update. I think it should work so that
1) hitting enter/a REPL eval sends an update of what variables are in the current module [here](https://github.com/ZacLN/julia-vscode/blob/refactor/scripts/terminalserver/terminalserver.jl#L27)
2) This message is picked up on the TS side [here](https://github.com/ZacLN/julia-vscode/blob/refactor/src/repl.ts#L145)
3) This should update the TreeDataProvider (this I haven't worked out)
After this is all working we should be able to set it up to click on …

split weave/repl functions into seperate files

---

package.json
src/extension.ts
src/repl.ts

The new command executes the toplevel block that the start of any selection sits in. We may want to give options to determine code eval behaviour. e.g.:
- if there's a selection, eval it
- if no selection do we eval the line or block?
Also switches context back to the active editor after any eval

add execute block command, return to active editor after any execution

---

src/extension.ts
src/openpackagedirectory.ts
src/packagepath.ts
src/repl.ts
src/settings.ts
src/smallcommands.ts
src/tasks.ts
src/weave.ts

This should fix the issue that the rearrangement of the typescript files broke the plotting stuff. I actually think it also broke a number of other things :)
This PR ends up being quite large because I did a whole bunch of things:
- split more things out into their own files
- only use classes where we need to, for now it seems easier to just stick with globals in modules, we can still change that later
- I introduced a general pattern how new features can live in their own file
My gut sense is that we can merge this soonish, but then we need to make sure we actually test all the features we have with the new version to make sure we 1) fixed the things that were broken and 2) I didn't introduce new bugs.

Fix typescript rearrangement

---

scripts/terminalserver/terminalserver.jl

Fixes #314.
Problem was that we need to send the length in terms of bytes, but we were sending the length in terms of characters. As soon as there is any Unicode character in an SVG file, things break :) This now fixes things.

Fix error in plot message encoding

---

src/repl.ts

@ZacLN I think this should fix the problem that the current editor is opened in column one if one sends any code from the editor in column two to the REPL. It actually had nothing to do with plots, it happened for all code.

Fix repl window focus

---

package.json

Alright, I just miss Ctrl+Enter for "execute current line" too much to not give it a default binding :) Plus, Alt+Enter is free, so we can use that for execute block.
Plus, it means we don't have any breaking change.

Use different keyboard shortcut for run block

---

src/repl.ts

This should fix #386 and #385.
@ZacLN There are at least two issues with the old version: 1) any error in the user code will kill the task that processes messages. We could put the ``eval`` into a ``try catch`` block, but then we would also need some code that displays an error message etc. Seemed all too complicated at this stage. 2) F5 would execute the saved file, not the stuff in the editor.
I think for now this PR might be the easiest and safest fix?

Fix bug in execute file

---

package.json

This is not great, but should be good enough for the 0.9.0 release, and then we can revisit in a future release.

Make julia.runlinter a window scope setting

---

src/juliaexepath.ts

using `julia` might trigger error in some case. Use full path works fine.

use full exec path

---

scripts/weave/run_weave.jl

`chomp` is a keyword argument of readline now and defaults to `true`:
[julia #20203](https://github.com/JuliaLang/julia/pull/20203)

readline automatically chomps

---

syntaxes/juliamarkdown.json

This doesn't introduce special handling for jldoctest but it's an improvement I think.

Highlight jldoctest blocks as julia in juliamarkdown files

---

src/repl.ts

Before this would spin in the REPL for minutes.
After:

fix pasting into REPL

---

src/repl.ts

Fixes #610.
This would replace #622. I think I would prefer not to add an option for this, instead I think we should use this on platforms where it works and not where it doesn't work, but really we should figure that out.

Fix sendText call on Windows

---

src/repl.ts

I was having an issue with the plot panel. I wanted to write code in one editor column and have the plot panel in another editor column. When I manually moved the plot panel to a second column and redraw the chart, the column disappeared and the plot panel covered my code. 
This PR attempts to fix this so we can leave a plot panel open in another column. Plotting again plots to the same column wherever you put it.
Note: I am getting some errors messages that the extension has crashed (it might just be on my side), so let's have a close look and test it out before merging, but wanted to submit to see what you think.

Preserve webview panel column

---

src/repl.ts

@EricForgy I think that should fix the bug you mentioned on Slack?

Release keyboard bindings after plot pane is closed

---

package.json
src/juliaexepath.ts

This allows specifying the julia binary in `julia.executablePath` without full path by searching the PATH environment variable.
Fixes #687
Note that I did not update `package-lock.json` because `npm install` removes all the caret symbols from version specifications for me, probably because I'm [using a different npm version](https://github.com/npm/npm/issues/20434).

Search for `julia.executablePath` in PATH

---

src/telemetry.ts

I have set both
"julia.enableCrashReporter": false,
"julia.enableTelemetry": false,
and was surprised to be asked to send a crash report. From the JuliaCon talk and the [privacy policy](https://github.com/JuliaEditorSupport/julia-vscode/wiki/Privacy-Policy) I assumed that `enableCrashReporter` followed the same logic as `enableTelemetry` (nag unless set to `false`). This PR fixes that. Do note that I could not test this as I don't know how to willfully trigger a crash.

Allow permanent opt-out of crash reports

---

package.json
src/repl.ts

Closes https://github.com/JuliaEditorSupport/julia-vscode/issues/689
Add support for custom command line arguments to julia, where one specify an array in the viscose settings.json, like
```
"julia.additionalArgs": [
"-O3"
],
```
Also, changes `-q` to `--banner=no` since one may need see repl warnings

additional julia command line args

---

scripts/terminalserver/terminalserver.jl
src/repl.ts

Only use one named pipe for all messages from julia to the extension and make the communication protocol more robust. Replaces #495.
@ZacLN I'm probably going to merge pretty soon because this is only the first step in a series of things I want to change. In particular, I want to finally change our code execution model so that we no longer just send the text to the REPL, but send the code via the pipe and can then execute it with more context information (so that things like `@__DIR__` etc work).

Streamline communication with REPL

---

scripts/terminalserver/terminalserver.jl
src/repl.ts

This fixes how we start up the REPL, so that now all communication channels are operational when `startREPL` returns.

Return from startREPL once all sockets are started

---

scripts/terminalserver/repl.jl
scripts/terminalserver/terminalserver.jl
src/repl.ts

Fixes #105. Fixes #394. Fixes #443. Fixes #481. Fixes #496. Fixes #506. Fixes #539. Fixes #595.
With this PR we now have two distinct ways to run code: a) send to REPL and b) execute code.
Send to REPL is unchanged to what we had previously, but "execute code" now transfers the code via a pipe to the REPL process and runs it there. Code run that way is much more robust: things like `include` will pick up the correct path, `@__DIR__` and friends work etc.
I think we should keep "send to REPL" the way it is, it also seems useful.
"execute code" currently does not echo the code that is being executed. I'm not sure that is the right choice, but thought we could try that for now. "execute code" also currently doesn't `display` the result of the executed code, which might also not be what we …

Add new execution model

---

src/repl.ts

Always annoyed me that I show a plot from the REPL and the REPL loses focus. No longer.

Preserve focus when plot pane is shown

---

package.json
src/jlpkgenv.ts

Fixes #728.
@tribut This takes the next step from your PR we recently changed. The main difference now is that I no longer activate auto activate an environment if there is no `Manifest.toml` present. I played with the implementation that did for a while, and I think one ends up with a sub-par experience. But, one can still pretty easily opt-in to opening a package and automatically getting that `Project.toml` activated as an environment: one just needs to instantiate the env once (thus creating a `Manifest.toml`) and then it will get auto activated.
But the main feature of this PR is that it adds a workspace level setting that stores the env that one selects via the UI, so that this setting gets persisted.

Add environmentPath configuration setting

---

scripts/tasks/task_docbuild.jl
src/tasks.ts

This should make things somewhat more stable, and it no longer creates a `Manifest.toml` in the docs folder every time one builds the docs.

Run doc build on temp copy of Project.toml from docs

---

scripts/languageserver/main.jl
scripts/languageserver/packages/Manifest.toml
scripts/languageserver/packages/Project.toml
src/extension.ts

This should generally be more standard and work with packages that only have a `Project.toml`.

Fix code loading

---

package.json
syntaxes/julia.json

Adds support for non-standard string literals for `js`, `R`, `py`, and `md`. This catches us up with additions to the grammar for atom-language-julia.
In addition to highlighting, snippets and language-appropriate commenting work as expected for the embedded language.
Pinging @haberdashPI as he has several extensions that add most of these separately. Given that Atom is including them by default, I thought maybe we should, too. If there's a consensus, I can also add `mat"` (one that @haberdashPI has that is not implemented here). David, you used more complicated regex's. If those fix problems over the basic versions included here, please bring that up.

Add highlighting for several languages embedded as strings

---

package.json
scripts/tasks/task_compileenv.jl
src/jlpkgenv.ts
src/repl.ts
src/tasks.ts

This adds experimental support for custom sysimages. There are two parts to this:
- A task that builds a custom sysimage for the current environment and stores that as `JuliaSysimage.dll` alongside the `Project.toml`.
- A configuration setting (off by default) that enables a logic where we start new REPLs with a custom sysimage if there is a file `JuliaSysimage.dll` in the same folder as the `Project.toml`.
This all only works if PackageCompiler.jl is installed. I might look into ways to cut that dependency at some point in the future, but I think for now this is ok, given that all of this is labeled experimental.
@KristofferC if you have thoughts on this, I'd be really interested to hear them!

Support for custom sysimg

---

syntaxes/julia.json

@twadleigh, this is what I get if I just convert the latest version of https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/grammars/julia.cson to JSON. It is different than what you had put into https://github.com/julia-vscode/julia-vscode/pull/762. So, am I right to assume that you a) copied the syntax from atom, and then b) also made some manual modifications?
We generally can't carry manual modifications here in the repo. I want to be able to just periodically copy the latest version from atom, without any manual review. So I think if we want these manual modifications, then ideally you would submit them as a PR against the original, upstream https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/grammars/julia.cson, and then they will flow back to here …

Copy latest syntax from Atom

---

package.json
syntaxes/julia.json
syntaxes/juliacodeblock.json
syntaxes/juliamarkdown.json
syntaxes/update_syntax.jl

- Updates the syntax using the new script.
- Fixes #765.
- Fixes #770.
- Adds an injection grammar for highlighting julia code blocks in markdown.

Adds automatic transformation of atom-language-julia grammar.

---

scripts/languageserver/main.jl
src/telemetry.ts

We have a couple of error messages that are not comprehensible right now, and I think this should help.

Fix error reporting for multi line error messages

---

src/repl.ts

I now believe that I removed this on Windows for the wrong reason, and that a different fix that I added later fixes the problem that originally triggered me reverting things on Windows.
Fixes https://github.com/julia-vscode/julia-vscode/issues/826.
CC @KristofferC

Enable bracket paste on Windows

---

package.json

Copied a line from python extension https://github.com/Microsoft/vscode/blob/master/extensions/python/package.json#L17 so that we recognize [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) executable files without `.jl` extension.
Note: edited from github, didn't test it locally.

Support shebang

---

src/tasks.ts

I am unable to run the test suite in my environment, so I may have a TS syntax error here.  (I'll see if I can figure out how to fire it up.)  But the concept of adding the `env` option works - I tested by hacking my local js files in the extension.
Let me know if you'd rather have this packaged in an alternate branch, or what other contribution guidlines you'd like me to follow.

Adding NUM_THREADS to test environment

---

scripts/terminalserver/terminalserver.jl

Fixes #833.
This does not yet work because the `julia/getCurrentBlockOffsetRange` message to the LS seems to return a block that does not include any trailing `;`, and that breaks the logic in this PR here that would decide whether to display a result or not. @ZacLN, could you look into the LS implementation of `julia/getCurrentBlockOffsetRange` and maybe change that so that it includes trailing `;`?

Show eval return value in REPL

---

.gitmodules
scripts/tasks/sysimageenv/Manifest.toml
scripts/tasks/sysimageenv/Project.toml
scripts/tasks/task_compileenv.jl
src/tasks.ts

Seems much more robust in general. With this PR we also ship PackageCompilerX with the extension.
Only thing that isn't perfect yet is the question where does the compiler come from. I would still say we merge this now, as this is certainly an improvement over the status quo.
CC @KristofferC.

Switch to PackageCompilerX for sysimage

---

package.json
src/repl.ts

Individual files can be selected with the explorer context menu and sent to the REPL.

Add execute file to explorer context menu

---

src/extension.ts

No longer needed with https://github.com/julia-vscode/LanguageServer.jl/pull/482.

Remove custom LS progress reporting UI

---

src/juliaexepath.ts

1.4.0 has a new Windows installer with a different default path.

Change Julia 1.4.0 Windows path to new default

---

src/extension.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/848.
We should never run the LS process with a custom `JULIA_LOAD_PATH` setting. This makes sure that `Base.LOAD_PATH` in the LS process is always the default.

Shield LS from custom JULIA_LOAD_PATH

---

scripts/languageserver/error_handler.jl

A previous PR accidentally removed display of this.

Show stack trace for LS errors

---

scripts/terminalserver/terminalserver.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/1028.
We need to run Revise.jl before we execute code if it is loaded.
@timholy, does this look sane to you? This is essentially just the place that executes if someone selects some text in VS Code and then sends that for execution in the REPL. With this PR we call `Revise.revise()` before we execute the user code. One question: Was that API always around for Revise.jl, i.e. will this code work with any version of Revise.jl that has ever shipped?

Invoke revise in repl/runcode

---

scripts/terminalserver/terminalserver.jl

The previous approach didn't work if Revise.jl is part of some other stacked environment. I think this approach here is more robust: it will just try to load Revise if it is requested.

Fix Revise.jl loading

---

src/juliaDebug.ts

Fixes a bug report on discourse. Mac named pipe names have a length limit, and this gets us around that.

Use shorter pipename for attach debugger

---

scripts/debugger/debugger_requests.jl
scripts/debugger/debugger_utils.jl

Fixes #1089. Sort of, at least we no longer crash. There is still a problem that the breakpoint is misplaced somehow, but I'll track that in a new issue.

Properly load base files in debugger

---

.vscode/launch.json

That explains why F5 didn't properly compile the extension since the webpack stuff :)

Fix the launch config

---

scripts/terminalserver/terminalserver.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/1007.
For now it just looks exactly the same as if it was typed in the REPL, I think that is probably the least surprising way to do this.
We could add an option later on to turn this off, but I think as a default this makes most sense.

Echo Julia code in REPL before executing it

---

src/repl.ts

Fixes a bug reported on Slack. Apparently we can get invalidpositions from `selection.active`...

Validate a position

---

scripts/languageserver/main.jl

This is needed to make `master` work with the latest LS version.
Also, the `ENV["JULIA_DEBUG"] = "all"` should lead to a situation that `@debug` statements show up in output.

Adjust debug mode for LS

---

src/repl.ts

Without this the CI compile doesn't finish. Not sure why this is showing up now, probably I updated some TypeScript defs to the latest version. In any case, should be harmless, this isn't used right now in any case :)

Fix a bug in REPLTree

---

scripts/debugger/debugger_rcp.jl
scripts/debugger/debugger_requests.jl

Fixes a bug from crash reporting (yeah, we have crash reports for the debugger!).
The version of `findfirst` that uses a `Char` as the first arg doesn't exist pre Julia 1.3, so instead I'm now using a version that exists everywhere.

Use a version of findfirst that exists on all Julia versions

---

scripts/debugger/debugger.jl
scripts/debugger/debugger_rcp.jl
scripts/debugger/debugger_requests.jl

Turns out https://github.com/julia-vscode/julia-vscode/pull/1186 is a bug everywhere...
This is not super elegant but works everywhere. I plan to replace the communication code with JSON RPC very soon, so this is a short term bug fix.
We should merge ASAP because minimally master debugging is completely broken right now, not sure whether I had shipped the fix widely already.

Properly fix a bug

---

scripts/terminalserver/terminalserver.jl

This removes a whole lot of code that isn't currently used. Some of it might come back when we re-add features, but for now I just want to clean up a bit before I start to rewrite the communication part.

Remove dead code from REPL

---

.gitmodules
scripts/terminalserver/terminalserver.jl
src/juliaDebug.ts
src/repl.ts

Improves #1203.
Major changes:
- Uses JSON RPC
- We use the same implementation in the REPL that we use in LS on the Julia side (I moved the code into a package)
- On the TypeScript side we use the vscode-jsonrpc package
- We use only one named pipe instead of multiple in the previous version
- All the weird message format hacks are gone :)
- We vendor JSON.jl into the REPL process, which will be super useful for lots of other things as well
- I'm starting to move all the Julia packages that we ship into the folder `scripts/packages`, right now they are all over the place.
Once we have this merged, I'll also use this for the debugger communication.
I don't yet have the kind of callback implementation that Juno has. The main reason is that I realized that won't work in the simple form for …

Use JSON-RPC for REPL-extension comm

---

scripts/debugger/debugger_requests.jl

Fixes a bug from crash reporting. This essentially finishes the debugger if one tries to debug an empty file.

Handle empty file case in debugger

---

src/extension.ts

This is no longer used.
Also, maybe this will help with the invalid config request? Maybe one should only register handlers before the client actually listens for things? This is obviously fishing in the dark, but at this point I don't have any other ideas and this looks maybe slightly different than what other implementations seem to do, so maybe worth trying.

Remove a dead request handler

---

src/extension.ts

I'm not actually sure this is a great idea, would like to hear some feedback.
This adds a status bar item that says "Starting Julia Language Server..." that will disappear as soon as the LS is read to accept requests, for example requests to identify the current block for say the Alt+Enter command.
It does add busy UI, but on the other hand it might be useful until we fix the LS startup performance problems?

Add a status bar item for LS startup

---

src/extension.ts
src/interactive/repl.ts
src/jlpkgenv.ts
src/juliaexepath.ts
src/openpackagedirectory.ts
src/packagepath.ts
src/smallcommands.ts
src/tasks.ts
src/telemetry.ts
src/weave.ts

- make each sub file listen for those events
- now we don't need to modify extensions.ts when we add another feature
- ~~... and if we start to dispose things, those subscriptions will also just be cleared correctly~~ nvm, vscode will automatically cleans up subscription pushed into `context.subscriptions`, so these will be cleaned up correctly as is

refactor: listen for onSetLanguageClient, onDidChangeConfig event

---

scripts/terminalserver/gridviewer.jl
scripts/terminalserver/terminalserver.jl

I need this for https://github.com/julia-vscode/julia-vscode/pull/1003, but it seems useful in itself, so a separate PR.
This just adds the ability to view vectors and matrices with `vscodedisplay` in the grid.
I also replaces the error with a warning when one passes an unsupported type to `vscodedisplay`.
Finally, it moves the whole grid code into its own file.
Generally: be warned, the grid code is not great at all, and there is _a lot_ we can and should optimize eventually: a) chiefly lazy loading, b) use JSON.jl now that we have in in the REPL process, c) use a better format than this dataresources at least for the vector and matrix case.
But, for now, this just improves the situation as it stands right now :)

Rearrange code and add support for vector and matrix to grid

---

scripts/terminalserver/terminalserver.jl

What I did in https://github.com/julia-vscode/julia-vscode/pull/1258 was wrong, this fixes things.
This is high priority because our current `master` now shows a warning after each eval in the REPL :) It hasn't gone out to the release channel (good), but we need to merge this before we can ship a new version.

Fix how we handle unsupported types for vscodedisplay

---

.gitignore
.vscode/settings.json

let's exclude `dist` and `out` from workspace search.

update ignore settings

---

scripts/debugger/run_debugger.jl
scripts/error_handler.jl
scripts/languageserver/main.jl
scripts/terminalserver/terminalserver.jl
src/extension.ts
src/telemetry.ts

This segments crash reports into different roles: "Language Server", "Extension", "Symbol Server" and "Debugger". Makes it easier to filter things on Azure.

Add different cloudRole properties to crash reports

---

src/interactive/repl.ts

I believe `startREPL` always shows the terminal, so we shouldn't need an extra call to `show` in these cases.

Remove duplicate g_terminal.show calls

---

package.json

Small tweak to the description. The idea is that we don't use the work `execute` for the copy-paste situation, to somehow signal that this command is different from our other execute commands.

Tweak title for a command

---

src/interactive/repl.ts
src/interactive/results.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/1279 (the highlighting happens because of git lens in the first screenshot above).
Also makes our inline results compatible with git lens (as requested by @aviatesk).

improve inline results

---

src/interactive/repl.ts

This makes it possible to distinguish the special VSCode Julia REPL from some other Julia session that might be running.

"Julia REPL" as terminal name

---

scripts/terminalserver/misc.jl
scripts/terminalserver/terminalserver.jl

This makes two improvements to the Julia side of our rendering code (for inline results and the workspace):
- Removes ANSI control chars since we can't handle them.
- Improve performance for expensive (or even non-terminating) `show` methods by returning early once `limit` bytes have been written to the IO.

improve render/strlimit etc

---

.vscode/extensions.json

This adds the Julia extension to the list of recommended extensions, and excludes the insider extension. The latter because the whole debug F5 story of the extension doesn't work very well if the insider edition is installed.

Update recommended extensions

---

scripts/terminalserver/terminalserver.jl

`module Foo end` now once again works in the REPL.

fix toplevel statements in repl eval

---

scripts/packages/VSCodeServer/src/VSCodeServer.jl
scripts/packages/VSCodeServer/src/repl.jl

fixes #1328 by wrapping evaluation in our own functions (i.e. `evalrepl`)
accompanied with:
- cutting off internal calls from stacktrace
- use `include_string` and more graceful stack trace
and I've found the same kind of error can happen for `Main.ans` update, so fixed it as well.

fix repl again

---

scripts/packages/VSCodeServer/src/repl.jl

Removes the `LoadError` wrapper when displaying errors in REPL.

improve repl error printing

---

src/extension.ts
src/telemetry.ts

We have a whole number of crashes in the LS where we think that the client is sending us invalid positions. BUT, we are not sure, it could also be the case that the client is sending us invalid positions and we still have some bug in our document management story that makes the LS crash because we try to apply the positions we get from the client to the wrong doc version.
This PR adds diagnostics that might help us get to the bottom of this. It essentially adds a middle layer between the message communication between the client and the LS, and sends a trace if there is a position requested that is already clearly invalid on the client.
If it turns out that every crash report from an invalid position in the LS is preceded with one of these traces here, then we can rule out that the …

Add telemetry for invalid positions

---

package.json

I think right now any user settings are automatically also used in a remote setting, which doesn't make sense. I believe that with this change, a user setting wouldn't automatically be used for a remote session, but it would still allow a user to override the setting in a workspace specific setting.
Would fix https://github.com/JuliaLang/julia/pull/36257.

Mark julia.executablePath as machine-overridable

---

media/delete-inverse.svg
media/delete.svg
media/next-inverse.svg
media/next.svg
media/previous-inverse.svg
media/previous.svg
package.json

How about using VSCode's builtin [product icon](https://code.visualstudio.com/api/references/icons-in-labels), which will automatically adjusts to user's theme ?

use vscode-builtin icons

---

.gitmodules
scripts/packages/VSCodeDebugger/src/VSCodeDebugger.jl
scripts/packages/VSCodeServer/src/VSCodeServer.jl
src/scripts/updateDeps.ts

I used `DebugAdapter2` because otherwise it got difficult to switch between branches. Now that things are merged, this should be renamed back to the proper name.
I'm going to merge this without review: if something goes wrong, we'll know immediately, and this is one of those PRs that are painful to have hanging around, because of submodule updates.

Rename DebugAdapter2 to DebugAdapter

---

src/interactive/results.ts

- ban `null` and use `undefined` instead
- type things
- wrap uri comparison logic into a function
shouldn't change any behaviour.

minor improvements

---

scripts/packages/VSCodeServer/src/misc.jl

Fixes a crash reporting bug: `isnothing` doesn't exist on Julia 1.0.

Replace isnothing with comparison

---

package.json
src/interactive/documentation.ts

This is a grab-bag of simplifications for the doc browser. It needs https://github.com/julia-vscode/LanguageServer.jl/pull/791 to work.
Here is what I changed:
- Instead of sending messages, we now use command URIs for links. That is much less involved and I think how this kind of problem is supposed to be done from an API point of view.
- The webview is now entirely stateless, so we don't need any state management anymore. That is also a recommendation for how one should use web views.
- I store the last position of the webview in global state, so that this is remembered across sessions. This allows us to remember the position, without having to deal with the state serialization stuff, i.e. we can still be entirely stateless.
- I added `g_` for all global variables
- I removed a couple …

More simplifications for doc browser

---

scripts/packages/VSCodeServer/src/eval.jl
scripts/packages/VSCodeServer/src/misc.jl
src/interactive/results.ts

1. indent hover content instead of enclosing by code block
```julia
using Markdown
md = @doc sin
md.content # <- hover over this would look weird without this PR
```
2. preserve whitespaces in inline result
```julia
"       " # <- inline result will only show one-whitespace without this PR
```

rendering improvement

---

package.json
src/interactive/results.ts
src/utils.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/1396.
Adds the `Clear Inline Results in Editor` command to the text editor title context menu:
Also uses `Escape` for clearing the current inline result (without messing with other keybindings too much) *and* improves the removal logic a bit.

improve result interaction

---

package.json
src/debugger/debugFeature.ts
src/extension.ts

Implements an [upcoming recommendation](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_47.md#single-file-debugging).
Also moves all the debugger code out of the `extension.ts` file and into a class.

Add run and debug button and move code around

---

src/docbrowser/documentation.ts
tsconfig.json

A few improvements against #1458 
- add `dom` library for TS compile, which will make CI pass again
- ~disable no-longer needed command URI option~ nvm: we will use this in the future for handling links, etc
- simplify the get/set documentation logic
- handle "no-editor" case

few more cleanups against #1458

---

package.json

This is where they belong, but we needed to wait until the release of VS Code 1.47, where this starts to be supported.

Put the run and debug button in proper nav group

---

src/interactive/repl.ts

This is an alternative to https://github.com/julia-vscode/julia-vscode/pull/1473, maybe we should try this PR here first and see whether it gets rid of the crash reports.
The idea is that we don't want any `await` between recording the position from the selection and the call to `getModuleForEditor`.
I think this particular problem should not occur [here](https://github.com/julia-vscode/julia-vscode/blob/master/src/interactive/repl.ts#L343), but that whole code section should probably also be reviewed for other type of race conditions later.

Fix a getModuleForEditor race condition

---

scripts/packages/VSCodeServer/src/eval.jl

Fixes a bug from crash reporting.
Currently a bug in a user defined `display` method crashes us, this puts in the necessary try catch block to prevent that.

Wrap a call to user code in a try catch

---

package-lock.json
package.json
src/juliaexepath.ts

This is a minimal bug fix that solves the most immediate problem with our julia.exe binary search: currently, if something goes wrong with that search, an uncaught error can escape the `getJuliaExePath` function. Because that one is called early on in the `activate` function of the extension, that interrupts the core initialization of the extension if one of those error situations occurs. This is _really_ bad because even if the user later changes the user config setting for the julia binary path to a valid value, the extension initialization is broken and nothing works.
There is a lot more we should do, but I think those other things should come after Juliacon: a) we should provide a proper UI story when the extension can't find a julia binary, b) we need to harden every part of the …

Handle errors in julia binary search

---

scripts/packages/VSCodeServer/src/eval.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/1474 (in that we now correctly throw a display error) and fixes https://github.com/julia-vscode/julia-vscode/issues/1468 (by only unwrapping at most one `LoadError`).

Fix error handling

---

src/interactive/modules.ts
src/interactive/repl.ts

The only other potential place that I could find where there might be an `await` between recording the selection position and recording the version of the document was in the default handling of `getModuleForEditor` itself. It is an async function, and it is not clear to me at which point the default argument is evaluated in those situations: pre or post the await call happening. So this could be another source of the discrepancies that we seem to be having.
I also changed the argument to be the doc itself, maybe that also helps, who knows.
If that doesn't fix it, I'm kind of out of ideas :)

Fix another getModuleForEditor race condition

---

scripts/terminalserver/terminalserver.jl

We have load revise by default `true`, so in a vanilla installation users will get a warning, which is not a good user experience. For now, just remove the warning. Will no longer be needed if we manage to ship Revise out of the box.

Remove Revise load warning

---

src/interactive/repl.ts

let's go this way for now, I don't think we need to be so strict on handling the empty editor case

quick fix for #1500

---

package.json

@ZacLN  are you ok with this? I think we just have too many complaints on the forums about false positives, so maybe we should just disable this by default for now, until we fix the environment story.

Change default for missingrefs to none

---

package.json
src/extension.ts
src/interactive/repl.ts

Now that Julia 1.5 is out it probably makes sense to allow the package server to be set from within VSCode. Setting it in `startup.jl` takes precedence, of course.

package server setting

---

package.json
src/interactive/repl.ts

Fixes the part of https://github.com/julia-vscode/julia-vscode/issues/1593 we can fix (persistent terminals without a wrapper process require upstream support).

add stopREPL command

---

images/julia-dots-outline.svg
package.json

Fixes #1601 
The new svg was crafted based on the vscode spec and on `images/julia-dots.svg`. After that change `images/julia-dots.svg` is not used anywhere, it can removed.
Before (left) and after (right) in light and dark themes:

Changed activity bar from filled to outline

---

package.json
src/debugger/debugFeature.ts

Currently these commands will result in an error when we call them from command (not via icon).
Will use active editor as fallback resource.

enable run/debug julia file via commands

---

scripts/packages/VSCodeServer/src/eval.jl
scripts/packages/VSCodeServer/src/repl.jl
scripts/packages/VSCodeServer/src/repl_protocol.jl
src/interactive/repl.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/1556.
This implements the following behaviour on Julia 1.5+ (everything stays the same on older versions):
- The REPL always uses softscoping.
- Inline evaluation always uses softscoping.
- Evaluating the whole file with `Julia: Execute File` always uses hardscoping.
I thought about making this user configurable, but I don't think that's a good idea.

softscope on Julia >=1.5

---

src/interactive/modules.ts

Currently our status bar is initialized as `Main` whenever REPL is active or an active workspace item is Julia editor or not. This PR fixes them by using the same function everytime we need to update status bar item.

update the module status bar item correctly

---

scripts/packages/VSCodeServer/src/eval.jl

This broke at some point in the past; seems we now need two new lines instead of only one for proper list rendering.

fix stacktrace rendering

---

scripts/packages/VSCodeServer/src/display.jl
src/interactive/plots.ts

Now opens plot pane in a different column instead of the current one. Also adds an unhandled disposable to the global subscriptions.

plot pane tweaks

---

scripts/packages/VSCodeServer/src/trees.jl

We now show an informative error in the workspace for errors somewhere in the lazy tree view display:
This also only special cases `Base`s `Array` and `Dict` types instead of all `AbstractArray`s and `AbstractDict`s, so that e.g. `ODESolutions` are displayed properly:
It also makes super duper extra sure that every index is assigned when showing arrays -- in theory this shouldn't be necessary since `prod(size(x)) == length(eachindex(x))` holds for `Array`s, but can't hurt either.

improve workspace error handling

---

src/extension.ts
src/juliaexepath.ts

This makes it possible to use `direnv` with the VSCode extension by setting `Julia: Executable Path` to the following script:
```bash
!#/bin/bash
export DIRENV_BASH=/bin/bash
exec /bin/direnv exec "${JULIA_VSCODE_WORKSPACE}" julia "$@"
```

Set JULIA_VSCODE_LANGUAGESERVER=1 for language server processes.

---

scripts/packages/VSCodeServer/src/VSCodeServer.jl
scripts/packages/VSCodeServer/src/display.jl
scripts/packages/VSCodeServer/src/eval.jl
scripts/packages/VSCodeServer/src/repl.jl
scripts/packages/VSCodeServer/src/repl_protocol.jl
scripts/terminalserver/terminalserver.jl
src/interactive/repl.ts

This makes the plot pane setting apply instantly without needing to restart the Julia process. It's also much more robust against other packages trying to inject their own displays above ours.
Also simplifies a bunch of `display`/`displayable` definitions.

fix plot pane setting

---

package.json

We've gotten a bunch of reports of people being annoyed/confused about the play button starting a new process/taking a long time/not using the correct launch config (this last one is because of a VSCode bug, I think).
This switches it to the in-process "Run File" command, which imho people should be using anyways. It also changes the names for "Run File"/"Debug File" to clarify that those start a new process.

default play button to "run file"

---

scripts/packages/VSCodeServer/src/eval.jl
src/interactive/repl.ts

Alternative to https://github.com/julia-vscode/julia-vscode/pull/1733 -- this shows an indeterminate progress indicator when evaluating anything inline. Also shows a `Cancel` button, which throws an interrupt at Julia (can't guarantee that'll end up in the actual `@progress` loop, but whatever).

interrupt evaluation from progress monitor

---

src/interactive/repl.ts

`@edit` is currently broken when running the extension in a [code-server](https://github.com/cdr/code-server) process. This fixes the path to the `code-server` binary and shouldn't affect anything else.

fix code-server binary path

---

scripts/debugger/run_debugger.jl
scripts/terminalserver/terminalserver.jl

Otherwise we can end up loading the wrong version of VSCodeServer, depending on how `LOAD_PATH` was set.

pushfirst/popfirst LOAD_PATH

---

package.json
scripts/packages/VSCodeServer/src/eval.jl

if `codeInREPL` is set.
Fixes https://github.com/julia-vscode/julia-vscode/issues/1752.
I thought about putting this behind another setting, but it feels fairly intuitive to reuse `codeInREPL` for this.

add inline-eval'ed code to repl history

---

scripts/packages/VSCodeServer/src/eval.jl

Might fix the weird off-by-one result error in the REPL that got reported on Slack at some point.

switch to unbuffered channels for eval

---

src/extension.ts
src/interactive/modules.ts
src/interactive/repl.ts
src/jlpkgenv.ts

This triggers the `onSetLanguageClient` event right away, not when the LS is ready, which allows consumers to `await` the ready state instead of having to return early. So with this patch you can use inline evaluation straight after starting VSCode without an error message; it will be evaluated after both the LS and the REPL process are ready.

improve LS startup interaction with inline eval

---

package.json

I was trying to get the REPL to start in a specific directory, so I was trying out different settings for `julia.environmentPath`. But I was just restarting the REPL, so it looked like `julia.environmentPath` was not having any effect. Thanks to @aviatesk on Slack I now realize what's going on (I incorrectly assumed that the environment settings applied just to the REPL), but it might be good to mention something like this.

Note that julia.environmentPath needs a VS Code reload to take effect

---

src/interactive/repl.ts

Allows keybindings like
```
{
"key": "ctrl+shift+t",
"command": "language-julia.executeFile",
"args": "/home/pfitzseb/test.jl"
}
```

allow string arg in executeFile

---

src/debugger/debugFeature.ts

This allows the `runEditorContents` and `debugEditorContents` commands to run in multi-workspace setups.

multi-ws support for run/debug commands

---

scripts/packages/VSCodeServer/src/eval.jl
scripts/packages/VSCodeServer/src/misc.jl

Turns out I broke this in the last release.

fix bt cropping for inline results

---

README.md

Currently the "Getting Started" instructions do not look right when I open the extension in VS code. I think this is because the list of instructions is not indented correctly. This PR fixes that.
For the record here is what it currently looks like for me:
where you can see the numbering is thrown off by the lack of indentation.

Fix ReadMe Getting Started list numbering

---

package.json
src/interactive/repl.ts

This adds commands to move to next and previous cell (part of #1278).
I assigned the shortcuts `ctrl+alt+[` and `ctrl+alt+]` to match the vscode python extension, although the behavior matches Juno (moving to previous cell moves to its last line, rather than the first).
Another option is alt+arrows, like Juno, but vscode uses those for "move line".

Cell move commands

---

package.json
src/interactive/results.ts

This will help with accessibility and reasoning about code structure.
To consider :
- Naming of configuration strings, which will be hard to deprecate.
- Whether to allow users to bind colors to [theme colors](https://code.visualstudio.com/api/references/theme-color). The `vscode.` prefix is necessary because programmatically verifying theme colors is unsupported. Prefixing seems mostly consistent with [other areas](https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content) of the API.
Other notes : 
- Currently proposes that we refer to the left border as "accent", since at some point we may want to somehow support an all-around border -- these seem to be more central in high contrast color themes. 
- In settings, I wanted this to follow logically after `Julia > …

Color Customization for Inline Result Bubbles

---

src/interactive/repl.ts

Got a report on Slack that the VSCode insiders binary is named `code` instead of `code-insiders` on MacOS nowadays.

fix code insiders binary name on macos

---

package.json
scripts/packages/VSCodeServer/src/display.jl

This makes sure that PyPlot works as expected (after a restart, that is).
Fixes https://github.com/julia-vscode/julia-vscode/issues/1782.

Fix displayable overloading

---

src/extension.ts
src/telemetry.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/514.
I think we have enough users opting into telemetry without a nag message now, so let's go with this as a more user-friendly alternative.

Improve telemetry dialogues

---

package.json

`@` and `!` are part of identifiers in Julia, so they shouldn't be in the list of word separators. Fixes https://github.com/julia-vscode/julia-vscode/issues/1860.

better word separators for Julia

---

src/interactive/modules.ts

This might fix [this](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode-insider%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%2FresourceGroups%2FDefault%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fjulia-vscode-insider%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22b00403d9-58ff-11eb-b315-7be397f49349%22%2C%22timestamp%22%3A%222021-01-17T20%3A07%3A55.645Z%22%2C%22cacheId%22%3A%22de8c4cec-9f05-4825-85de-40c5e928d6ed%22%2C%22eventTable%22%3A%22exceptions%22%7D).
My theory …

Fix a race condition

---

package.json
scripts/environments/pkgdev/Manifest.toml
scripts/environments/pkgdev/Project.toml
scripts/packagedev/tagnewpackageversion.jl
src/extension.ts
src/packagedevtools.ts

This makes the `tag` functionality from PkgDev.jl available through the extension.
I'm pretty sure there are still some corner cases that this doesn't handle properly, and we could probably also improve on the UI, but on the other hand it really, really simplifies tagging a new version :) And one major benefit of using this from VS Code rather than directly as a package is that we can get the authentication info from VS Code, so that is a lot less brittle than the normal way in PkgDev of trying to get the credentials from the git credential manager.
Not sure, should we maybe just merge and leave it with the `experimental` label and then fix things as they come up?

Add support for tagging package versions

---

.gitmodules
scripts/packages/VSCodeLiveUnitTesting/src/VSCodeLiveUnitTesting.jl
scripts/packages/VSCodeLiveUnitTesting/src/copied_from_test_reports.jl
scripts/tasks/task_liveunittesting.jl
src/tasks.ts

This adds a new task that does "live unit testing". Essentially it runs the tests in your package, and whenever one edits the tests or the package and saves, it reruns the test suite.
I think there really is only one thing to figure out:

Live unit testing

---

package.json
scripts/packages/VSCodeLiveUnitTesting/src/VSCodeLiveUnitTesting.jl
scripts/tasks/task_liveunittesting.jl
src/tasks.ts

If one has a test suite that genuinely takes a long time to run, then this options allows one to specify a different test file that has some unit tests that might run quicker specifically for live testing.

Add option for live test file

---

src/interactive/plots.ts

With CairoMakie I'm usually annoyed that SVG's are not scaled and therefore shown way too big / cut off. Also, png images are scaled to fit but only horizontally, so if the plot pane is rather wide but not tall, images are cut off at the bottom.
This tries to fix both of those problems.
SVG's are put into an image tag if they appear to be valid for that purpose (have the xmlns tag). This image tag is then scaled such that the image either vertically or horizontally fits into the plot pane if the image is bigger than either dimension.
If the image is shorter in both dimensions than the available space, it is not scaled but shown at its true size (via `object-fit: scale-down`).
Here are two examples showing how a big svg is scaled:
```julia
let
svg = …
```

better plotpane image scaling

---

scripts/packages/VSCodeLiveUnitTesting/src/VSCodeLiveUnitTesting.jl

This now sets the pwd to be folder where the test script is located in.

Set path for live testing properly

---

src/tasks.ts

Hopefully this should fix #1895. 
I'm not too sure what to put for the name and directory of the results file, or if there is some way of having the user pass this into the task as an argument. At the moment I've set it to save it in the benchmark subdirectory as that seems to make sense to me, but if anyone knows what the old behaviour was it might be worth changing it to match that.

Fix for #1895 Benchmark task MethodError

---

src/tasks.ts

I think we won't be able to fix https://github.com/julia-vscode/julia-vscode/issues/1900 super quickly, so I think we should move the live testing stuff to the 1.2 release. This disables it for now.

Disable live testing

---

src/debugger/debugFeature.ts
src/extension.ts
src/interactive/repl.ts
src/jlpkgenv.ts
src/tasks.ts

This is a follow-up to https://github.com/julia-vscode/julia-vscode/pull/1903.
My previous attempt meant that if one has a relative path in a local settings file, then it would immediately changed to an absolute path in the settings file when the extension started. That seems undesirable: we want the ability to store relative paths in the settings, but then we want to have absolute paths passed to every place where that value is used. This PR should enable this.

Allow persistance of relative env paths

---

src/extension.ts
src/jlpkgenv.ts

This verifies the user supplied env path before returning it in `getAbsEnvPath`. Falls back to the default env path if verification fails. Also properly hides the startup notification if we fail early in `startLanguageServer`.

more env improvements

---

scripts/packages/VSCodeServer/src/misc.jl

fix find_toplevel_scope in the REPL

---

package.json
src/interactive/repl.ts

Alternative to https://github.com/julia-vscode/julia-vscode/pull/1929.

only show explorer context menu entries when REPL is running

---

scripts/packages/VSCodeServer/src/eval.jl

Fixes fun behaviour like
```
julia> Base.unwrap_unionall(Array)
TypeError(:new, "", UnionAll, Array{T,N})
```
for some reason.
Also hopefully fixes https://github.com/julia-vscode/julia-vscode/issues/1954.

unparametrize wrapper

---

README.md

I didn't notice "experimental" in the docs, only in the README, and just thought it might be outdated with version 1.0 out (and seeing debug issue closed). If not ignore or close. All software may have bugs or missing features, but seeing "experimental" may put people off.
In general I would like to know where VSCode extension has feature parity with Juno (and well anything else used for Julia) or is better.
Such as for the debugger, linter, plotting etc. All considered at least non-experimental? I kind of liked the way in Juno to highlight code to run and getting checkboxes. Is it on the agenda or already there somewhere with non-default option?
I do not really care what implements the debugger if it just works. Is there one built-in go to option, this one (or as an option?): …

Debugger no longer experimental?

---

CHANGELOG.md
src/weave.ts

Weave.jl does not properly respect the out_path option and instead uses
it to determine the output directory. There should probably be a fix
in Weave.jl at some point.
Fixes #1683.

Fix for Weave preview

---

scripts/error_handler.jl

Alternative to https://github.com/julia-vscode/julia-vscode/pull/2014. I think right now things might fail if the `connect` call for the error reporting pipe doesn't work, and with this `try finally` we should protect against that.

Make global_err_handler a bit more robust

---

src/notebook/notebookFeature.ts
src/notebook/notebookKernel.ts

@donjayamanne I think this takes care of the proper startup behavior for the kernel. With this it also works that if one kills the kernel by killing the corresponding terminal, a new kernel will be started at the next cell execution.

start-kernel-when-execute

---

src/notebook/notebookKernel.ts

Else we end up with invalid state & appending to existing output.

Clear existing cell output and metadata

---

package.json
src/interactive/repl.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/2057. 
This basically makes `get_editor` a bit dumber, but more robust and user overrideable.

Fix JULIA_EDITOR

---

README.md

Fixes #2079 
This pull request adds instructions to set up the extension from source for developers. _(and some minor markdown spacing fixes)_

Add developer instructions in README.md

---

CONTRIBUTING.md
README.md

@davidanthoff
1. Update README.md to include a link to contribution guidelines.
2. Move the developer instructions from README.md to CONTRIBUTING.md

Move developer instructions in CONTRIBUTING.md

---

scripts/packages/VSCodeServer/src/eval.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/1924. Tested this on 1.0, 1.5, and 1.6 -- seems to work decently well on all of them.

fix stacktrace rendering on 1.6

---

src/debugger/juliaDebug.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/527.

fix nthreads for external processes

---

scripts/packagedev/tagnewpackageversion.jl
src/scripts/updateDeps.ts

The tagging functionality is currently broken on Julia 1.6. I fixed things in PkgDev.jl, but things are now Julia 1.6 only.

Make package tagging Julia 1.6 only and improve update script

---

src/interactive/repl.ts
src/interactive/results.ts
src/juliaexepath.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/885, at least for the logging/stacktrace special case of
```
@ Base ./rational.jl:61
```
Works with relative (resolved inside of Base) and absolute paths.

add terminal link handler for julia specific link syntax

---

src/docbrowser/documentation.ts

We moved to `file://` links in LanguageServer.jl some time ago, which markdown-it filters out by default. This changes their URL validation to allow that.

Fix links in docpane

---

package.json
src/docbrowser/documentation.ts
src/interactive/plots.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/2172.
Focus is now mostly retained (except for the first time the navigator is displayed). Also added a setting to disable automatically showing the navigator.

plot navigator fixes

---

scripts/error_handler.jl
scripts/packages/VSCodeServer/src/VSCodeServer.jl
scripts/packages/VSCodeServer/src/debugger.jl

This stops connection errors from being propagated to crash reporting or the user, since these are mostly expected. If they are the cause of something going seriously wrong then we won't get anything useful out of them anyways.
Together with https://github.com/julia-vscode/DebugAdapter.jl/pull/39 this fixes the debugging experience.

improve disconnect handling

---

src/notebook/notebookFeature.ts

@davidanthoff This is required.
If you open a notebook today, some kernels can & will change the language of the cells. 
E.g. if you open a notebook and user changes the language to HTML for some reason or accidentally uses .NET kernel or the like, then the language of the cells can change.
If after running the cells the user realized the kernel is incorrect & change it from Python or .NEt to Julia, now the cells are not Jualia, we'll need to update them.

When using Julia kernel change code cells to Julia

---

scripts/packages/VSCodeServer/src/serve_notebook.jl
src/extension.ts
src/interactive/repl.ts
src/interactive/workspace.ts
src/notebook/notebookFeature.ts
src/notebook/notebookKernel.ts

This integrates the notebook kernels into our workspace view.
I'm going to merge this PR right away into the `notebook` branch, but this touches a couple of things that @pfitzseb is more familiar with than I am, so if you want to take a fairly isolated look how I changed the workspace implementation, then hopefully this PR makes that a bit easier to review.

Integrate notebook with workspace view

---

CHANGELOG.md
src/interactive/repl.ts

This PR fixes two issues for Windows platform related to creating links to files in the new stacktrace introduced in Julia >= 1.6:
1. Fix expanding of tilda symbol to the home path using the correct environment variable for Windows platform `HOMEPATH`.
2. Improve handling of paths containing spaces by improving the relevant regular expression.
**Handling of paths with spaces:**

Fix REPL stacktrace links for Windows platform

---

src/interactive/repl.ts

This is likely more robust than rolling our own ENV based solution.

use homedir() instead of env variables

---

package.json

Changes completionmode to `qualify` (so changes are always localized) and the inline result type to "both".

adjust a few default settings

---

scripts/languageserver/main.jl

This fixes the LS on 1.7.
The proper fix is https://github.com/JuliaLang/julia/pull/41653, but we should probably get this in regardless?

Explicitly set logger to stderr in LS startup script

---

scripts/packages/VSCodeServer/src/display.jl

to make display more responsive. We're doing the same for progress messages.

flush conn channel in display calls

---

src/notebook/notebookKernel.ts

@DonJayamanne, this errors because apparently one can only delete cell output during execution of a cell. I think we would really want to delete cell output when the cell gets queued, though, like in other Jupyter clients. Is there some way to do that?

Clear cell output when cell is queued for exec

---

src/notebook/notebookFeature.ts

This makes the kernel selection UI look like this:
So it shows our extension name, so that users understand where that kernel is coming from, and it also shows the Julia path that is used for that kernel.
@DonJayamanne and @claudiaregio, maybe the Jupyter extension could also set the `controller.description` field to something like `Jupyter extension`, then it would be even clearer where these kernels come from?

Provide better labels for notebook controller

---

package.json
src/notebook/notebookFeature.ts

So until we find a solution for https://github.com/julia-vscode/julia-vscode/issues/2256, the native notebook experience will write notebook files that don't save kernel information. In my mind this is a bit of a showstopper, anything where we write files that have a "bug" I think we should hide behind an experimental flag. I think users would get rightfully upset if we shipped something that writes incorrect files and then they have to deal with these down the road.
So, that is what this PR does. I would suggest we merge this and leave it in until upstream provides the necessary APIs to properly write correct Jupyter notebooks. And with this PR merged, we _can_ ship a version 1.3 to the release channel, though.
CC @DonJayamanne and @claudiaregio, if you have some other idea how we could …

Hide notebook feature behind a feature flag

---

scripts/packages/VSCodeServer/src/repl.jl

I think this fixes a source of https://github.com/julia-vscode/julia-vscode/issues/412 (and is generally just more correct).

fix hideprompt on 1.6 and newer

---

src/juliaexepath.ts
src/notebook/notebookFeature.ts

Replaces https://github.com/julia-vscode/julia-vscode/pull/2276.
@DonJayamanne I thought about this a bit more, and this is a quite different strategy now :)
The starting point is that I think we should actually register a controller for every Julia version that is installed, not just one per minor version. The "one per minor version" is something IJulia.jl does, but I don't really see any good reason for that in our case, I think we should just give users access to any Julia version they have installed.
From that it follows that we can't name our controllers `julia-1.6` because those names are not unique, we now want the ability to have a controller for 1.6.1 and 1.6.2 etc. I also now want to expose x64 and x86 controllers and a couple more things that will come once I integrate things …

Implement a new kernel selection strategy

---

.gitignore
.vscode/launch.json
scripts/languageserver/main.jl
src/extension.ts

With this the LSP process starts in debug mode when we debug the extension. Breakpoints in request handlers? Check!
Probably still a bit iffy, and the fact that the debugger doesn't handle `@async` will probably be a problem, but crudly it works and is probably already helpful.
@ZacLN just pinging you here to make sure you see this, I think this might make working on the LS a lot easier.

Add a debug launch for the LSP

---

.vscode/settings.json

It was actually not a local setting on my end, but the repo wide configuration that triggers the format on save.

Tweak settings.json

---

src/debugger/debugFeature.ts
src/debugger/juliaDebug.ts
src/interactive/results.ts
src/packagedevtools.ts

I'm going to tackle the entire strict typing mode for TypeScript, i.e. try to switch that on. For now this fixes a small number of problems discovered by that mode.
Once the new exe file search PR is merged, I'll try to convert the entire code base over to strict typing.

Fix some strict typing bugs

---

package-lock.json
package.json
src/debugger/debugFeature.ts
src/debugger/juliaDebug.ts
src/extension.ts
src/interactive/repl.ts
src/jlpkgenv.ts
src/juliaexepath.ts
src/notebook/notebookFeature.ts
src/notebook/notebookKernel.ts
src/packagedevtools.ts
src/packagepath.ts
src/scripts/updateDeps.ts
src/tasks.ts
src/weave.ts

Fixes #2294. Alternative to #2340.
This got a bit out of control ;) But I think it is now in pretty good shape, hopefully. Couple comments:
- It interprets the config value as a command now, not a path. So things like `julia +1.2`, full paths, just `julia` etc. should all work.
- We no longer try to resolve the path (except for the link stuff) at all. Instead, we now use the command throughout to start everything. We probably need to test every feature that spawns Julia on every platform to be sure it all works... Or have this on insider sufficiently long :)
- Startup should be much faster because we now only run `julia -v` essentially, instead of running actual Julia code.
- Here is my logic for whitespaces in the configuration value: first, I just test if the entire value in the config …

Rewrite Julia executable search code

---

src/interactive/results.ts

This might help us diagnose a crash reporting issue.

Use normal function syntax for gotoFrame

---

src/juliaexepath.ts
src/tasks.ts

Fixes https://github.com/JuliaLang/juliaup/issues/125.
This is a short term hack and I'll try to find a better way to solve this. The problem is this: in general, it seems, that tasks in VS Code don't work with anything that is MSIX installed on Windows and has an execution alias. I tested for example `winget`, and trying to run that also doesn't work. So this is almost certainly an upstream bug in VS Code itself. For now this hack works around that. It breaks the scenario where our config setting is something like `julia +1.2`, i.e. where the config setting is not just pointing to one executable, but rather a combined command. But given that we didn't support that in the past and didn't announce yet that we (thought)  supported that now, I think this hack is OK for now.

Use a hack to fix a tasks problem with juliaup

---

README.md

I think this is the easiest way to install the extension, which relies on the `vscode:extension/julialang.language-julia` url registered with the VS Code installation (on windows at least).
Fixes #.

Install from VS Code Marketplace

---

src/jlpkgenv.ts

Fixes the bug in getting default env. The original code doesn't work on win or linux.

split getDefaultEnvPath execFile args

---

src/jlpkgenv.ts
src/juliaexepath.ts
src/packagepath.ts

This continues the work started in https://github.com/julia-vscode/julia-vscode/pull/2372.
At least on my system things are _really_ broken without that. I don't understand why that is coming up now... Maybe it has something to do with `juliaup` and that that requires properly escaped arguments, not sure... In any case, the theory here is that `execFile` handles all subtleties of quoting and escaping for us. I hope that is right :)

Fix arg passing to Julia

---

README.md

It does not appear this badge is setup to work with anything so we should remove it or update the link it points to.

Remove Azure pipeline badge

---

src/juliaexepath.ts

The `Set` method doesn't work for objects, as it only deduplicates identical references.

Properly deduplicate the cachedJuliaExePaths

---

src/interactive/repl.ts

This ensure that we focus an already existing REPL when the `Start REPL` command is used.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2436

focus existing REPL in startREPLCommand

---

src/interactive/plots.ts

Fixes https://discourse.julialang.org/t/need-theory-on-why-svg-output-is-no-longer-auto-zooming-in-vscode-plots-pane/67985.

Fix svg plotting

---

src/interactive/plots.ts

- As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor), `all-scroll` cursor should be used for panning.

Unify plot-element style for all backends and use `all-scroll` cursor

---

CHANGELOG.md
README.md
package.json
src/interactive/repl.ts

Addresses #2349. This adds a single variable `$[workspace]` which is probably the most useful one to add.

Tmux session names: replace `$[workspace]` with current file's workspace

---

CHANGELOG.md
scripts/tasks/task_compileenv.jl

Fixes #1673
Default to exclude development packages during system image building. Also, allow passing additional options to the `PackageCompiler.create_sysimge` function based on a `vscode-compileenv.toml` file located inside the project root folder. 
This can be used to pass precompile execution/statement files and further reduced the first-call latency.

Impove the system image build script

---

package.json
scripts/packages/VSCodeServer/src/misc.jl
src/interactive/repl.ts

- cell evaluation now properly works in jmd files
- Julia keybindings now work in jmd files
- fixed an error when evaluating code strings only containing new lines
- fixed a cause of orphaned error highlights
Fixes https://github.com/julia-vscode/julia-vscode/issues/2466 and probably a bunch of other issues.

Various fixes for cell and inline evaluation

---

CHANGELOG.md
src/extension.ts
src/test/suite/extension.test.ts

Fixes #2149.
I just started learning Julia, so please correct me if I've misunderstood something.
This updates the indent regex so that indentation is triggered when `end` appears in the for loop as an index:
```julia
for i in nums[2:end]  # next line should be indented
```
The old regex seemed to be trying to look for closing brackets as an indicator. I think that wasn't working because it was actually doing a double negative when it only wanted one? I'm not really sure. I just removed that part and replaced it so that an indent will only not be triggered when `end` is followed by whitespace only (or no characters).
You can play with the new regex here: https://regex101.com/r/oAUCTC/1

Correct indentation when `end` appears within iterator definition

---

src/interactive/results.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/2521.

fix result validation with CRLF lineendings

---

src/interactive/repl.ts

Ran into an error when trying to run the newly released insiders. Turns out the current version doesn't properly replace `"` characters. (I was worried it was something to do with my changes in #2534, but it seems unrelated).

bugfix: correctly escape `"` characters when starting julia

---

CHANGELOG.md
package.json
scripts/packages/VSCodeServer/src/completions.jl
scripts/packages/VSCodeServer/src/profiler.jl
scripts/packages/VSCodeServer/src/tables/filtering.jl
scripts/packages/VSCodeServer/src/tables/tableviewer.jl
src/debugger/juliaDebug.ts
src/extension.ts
src/interactive/completions.ts
src/interactive/repl.ts

Fixes:
- runtime completions
- Weave keybindings
- error on empty profile traces
- tableviewer issues
- adds a uuid to "Run/Debug in new process" tasks, so that multiple can be active at the same time
and will try to kill the REPL when the extension is deactivated, which should help with the new VS Code persistent terminal issues.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2540. Fixes https://github.com/julia-vscode/julia-vscode/issues/2559.

Various fixes

---

CHANGELOG.md
src/interactive/plots.ts

This will be closer to how VSCode renders images.
See the difference in the rendering of the current behavior:

Use pixelated rendering for images in the plot pane

---

package.json

Fixes https://github.com/julia-vscode/julia-vscode/issues/2689.
This removes some of the duplicate keybindings to navigate the plot pane. With this,
- Left/Right will move to the previous/next plot
- Home/End will move to the first/last plot
Removed are the PgUp/PgDown/Up/Down keybindings, all of which go to the previous/next plot and are confusing in the context of the plot navigator.

Remove duplicate plot pane keybindings

---

package.json
syntaxes/julia_vscode.json

to fix a highlighting bug in the grammar shipped with VS Code 1.64 and 1.64.1
Fixes https://github.com/julia-vscode/julia-vscode/issues/2718.

Temporarily vendor Julia grammar again

---

package.json

Fixes https://github.com/julia-vscode/julia-vscode/issues/2757.
Using `/^julialang.julia\///` or anything like that *should* work, but apparently never returns true currently.

Add when clause to notebook toolbar icons

---

CHANGELOG.md
scripts/packages/VSCodeServer/src/VSCodeServer.jl

This enables the table viewer if TableTraits/DataValues is loaded before we connect (e.g. via a sysimg or by connecting to an existing Julia session).

Check loaded tables modules

---

src/packagedevtools.ts

This is now a bug because the env that is check into master no longer supports pre Julia 1.6 versions.

Add Julia version check for tagging feature

---

images/julia-dots-outline.svg

SVG 1.1 does not necessarily support the style element. The current
solution seems to work fine in Chromium derivates, but not in e.g. Firefox.

Fix toolbar icon

---

src/extension.ts

I haven't seen a crash report from this in ages, and it really was just a temporary diagnostic tool, so I think we can remove at this point. Just creates overhead.

Remove LS middleware

---

src/extension.ts
src/juliaexepath.ts

This makes things work when a user configures something like `julia +lts` as their exe. Right now that is broken because we start the LS with a special depot, and then juliaup tries to install julia versions into that special folder, which we don't want to happen.

Improve juliaup integration with LS

---

src/telemetry.ts

The old method no longer works.

Use correct telemetry env in debug mode

---

scripts/error_handler.jl

This should make it easier to look at crash reports on Azure.

Show error message first in crash report

---

src/juliaexepath.ts

Julia 1.6.6 is being tagged right now, so this keeps us one step ahead.

Add Julia 1.6.7 support

---

package.json
scripts/packages/VSCodeServer/src/repl_protocol.jl
scripts/packages/VSCodeServer/src/trees.jl
src/interactive/workspace.ts

This adds a 'Go to definition' button for modules and methods; it also adds all methods as children to their function.

'Go to Definition' for workspace items

---

src/notebook/notebookKernel.ts

This might fix a crash report. It seems that accessing the `fsPath` file tries to manipulate the uri instance, but it is read only or something like that...

Fix a readonly problem

---

scripts/packages/VSCodeServer/src/trees.jl

I think technically we would actually need to special case handle _any_ case anywhere in our code base where we take any value from a user provided function and turn it into a boolean via some function that one would expect to return  a bool... But this at least fixes one case that showed up in crash reporting.

Fix a case where missing introduces 3VL

---

scripts/packages/VSCodeServer/src/trees.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/2832.

Fix getvariables check

---

package.json
scripts/packages/VSCodeServer/src/repl_protocol.jl
scripts/packages/VSCodeServer/src/trees.jl
src/interactive/workspace.ts

Ideally this would use a toggleable menu entry, but those aren't available to extensions atm (ref https://github.com/microsoft/vscode/issues/148633).

Workspace: Add toggle to hide modules

---

scripts/packages/VSCodeServer/src/trees.jl

by using `===` instead of `isequal`
Fixes https://github.com/julia-vscode/julia-vscode/issues/2891.

Make getvariables more robust

---

package.json
src/interactive/profiler.ts
src/interactive/results.ts

Fixes https://github.com/julia-vscode/julia-vscode/issues/2883. 
Also removes the inline result color settings in favor of the colors contribution point (which means that themes can specifically style our inline results).

Make inline result and profiler colors themable

---

src/extension.ts
src/interactive/repl.ts

I believe that is the correct way to do async cleanup, plus the docs for the new LS client say we should do this :)

Return promise from deactivate

---

src/debugger/juliaDebug.ts
src/extension.ts
src/interactive/repl.ts
src/interactive/tables.ts
src/interactive/workspace.ts
src/jlpkgenv.ts

`sendNotification` now returns a promise, so we can actually catch errors if a notification can't be written to the underlying transport because it was already closed or something like that.

Use await for all sendNotification calls

---

package.json
src/extension.ts
src/interactive/repl.ts

This PR enables code evaluation in plain-markdown files (and also fixes some logic errors when the `inlineResultsForCellEvaluation` setting is enabled):
Requires https://github.com/julia-vscode/LanguageServer.jl/pull/1102.

Enable support for plain-md code evaluataion

---

package.json

Tiny change - the type of `julia.deleteJuliaCovFiles`` is specified as boolean, but default was assigned to string.

Fix type for default in `julia.deleteJuliaCovFiles`

---

scripts/packages/VSCodeServer/src/eval.jl
scripts/packages/VSCodeServer/src/repl.jl

- mutli-line inputs now work properly thanks to 633 E
- prompt refreshs now don't print multiple decorations (e.g. when deleting code)
Ref https://github.com/microsoft/vscode/issues/155315.

Various shell integration fixes

---

CHANGELOG.md
package.json

Fixes #2970. (Maybe. Untested.)
The scope of this PR extends a bit beyond #2970. It motivated the fix to the keybinding for `Escape`, but in the process revealed what is likely a similar error for other keybindings.

Added missing parentheses in "when" clauses of keybindings.

---

scripts/packages/VSCodeServer/src/repl.jl
scripts/terminalserver/terminalserver.jl

This is more correct, since it properly marks every prompt (exactly once).
It also enables shell integration on Windows (with a few conhost fixes enabled by `\e]633;P;IsWindows=True\a`), but the experience is still pretty wonky due to https://github.com/microsoft/terminal/issues/8698:

More shell integration fixes

---

scripts/terminalserver/terminalserver.jl

because it causes performance issues.

Disable shell integration on Windows

---

src/interactive/completions.ts

This should fix a bug from crash reporting.
I need to look into how to do this properly one day, I would actually think that a function that detects that it is cancelled should throw an error, but I haven't really been able to confirm that... For now this should fix things, though.

Fix a cancellation bug

---

scripts/packages/VSCodeServer/src/tables/tableviewer.jl
scripts/packages/VSCodeServer/src/trees.jl

because that eagerly aborts printing and is therefore less likely
to cause performance issues when objects with very large
representations are displayed in the workspace.

Use `sprintlimited` instead of `strlimit`

---

package.json

`s/Set's/Sets` — don't need an apostrophe there.

Typo fix in the Package Server setting description

---

src/interactive/modules.ts

Fixes the most frequent bug from crash reporting, I hope.

Check whether ls is ready in getmodule

---

src/extension.ts

Fixes bug where the user is pointed to the vscode environmentPath setting when I believe they should be sent to executablePath.
Not sure if this needs to be in the changelog. Can add if needed.

fix bug in extension.ts

---

src/debugger/debugConfig.ts
src/interactive/completions.ts
src/interactive/modules.ts
src/interactive/repl.ts
src/interactive/workspace.ts
src/utils.ts

Requires https://github.com/julia-vscode/LanguageServer.jl/pull/1176.
We are still getting crashes inside `getModuleForEditor` in crash reporting, apparently the check before the `sendRequest` whether the client is running didn't work properly. So this changes strategy to correctly use error codes to identify if the client wasn't running, which in general is a better way to handle this in an async world in any case. I also removed some nested try catch blocks that I didn't think make much sense and probably didn't work in any case as they did things like compare error message strings.
Easiest to review commit by commit, as this also adds additional error handling with crash report sending.

Fix more errors in get module

---

src/juliaexepath.ts

This patch adds some upcoming julia versions to the executable search such that the extensions is already ready when those are released. Without doing this it seems like it is always outdated (at least that is my experience when trying to guide students to set this up). And I know juliaup might be preferred, but the standard installer should still IMO work, and the current user experience is really bad...

Add some upcoming julia versions to executable search

---

src/notebook/notebookFeature.ts

Fixes a bug that prevented the logic from ever working.
Then also gives higher preference to `release` and `lts` channels if a user has more than one Juliaup channel for a given Julia version.

Improve notebook kernel selection

---

scripts/packages/VSCodeServer/src/eval.jl

Possibly due to changes to the REPl in Julia 1.9 ([news.md](https://github.com/JuliaLang/julia/blob/release-1.9/NEWS.md#repl)), the prompt is not just a string but can be a Union{Function, String, ...}
Uses [prompt_string](https://github.com/JuliaLang/julia/blob/c1d1bde5918c07fc377b7942c50329487d3e70ce/stdlib/REPL/src/LineEdit.jl#LL424-L425C50) to convert `prompt` to string, otherwise would cause problem in e.g. the length call in
https://github.com/julia-vscode/julia-vscode/blob/3dff67d8b2bbb7c579c04c466b89c333ec3dcc2e/scripts/packages/VSCodeServer/src/eval.jl#L145
Fixes #3220
Fixes #3235
Note: the prompt_sting function, while not exported, seems to be there since julia v1.0 [link](https://github.com/JuliaLang/julia/blob/e0837d1e64a9e4d17534a9f981e9a2a3f221356f/stdlib/REPL/src/LineEdit.jl …

fix multi-line exec to repl for julia 1.9

---

src/debugger/juliaDebug.ts

This doesn't actually change anything but does stop the error in the Output from appearing as reported in [#3618](https://github.com/julia-vscode/julia-vscode/issues/3168).
Fixes [#3618](https://github.com/julia-vscode/julia-vscode/issues/3168)

Change debug task type

---

scripts/packages/VSCodeServer/src/display.jl
scripts/packages/VSCodeServer/src/eval.jl
scripts/packages/VSCodeServer/src/repl.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/3387.
Also makes sure we 
- don't display errors in the REPL unless requested
- correctly set the `err` and `ans` globals on 1.10 and newer
- correctly set `err` for REPL eval

fix: use correct display logic for plots and errors

---

src/extension.ts
src/jlpkgenv.ts
src/juliaexepath.ts
src/packagepath.ts

I'm sometimes using a script that switches between a sysimg and no sysimg depending on whether the user process or the LS process runs (because the latter doesn't need to load the sysimg). This adds a new env var `JULIA_VSCODE_INTERNAL` that's set for all of these. It also adds `JULIA_VSCODE_LANGUAGESERVER` to the LS process, because that's slightly more descriptive.

feat: set JULIA_VSCODE_INTERNAL for internal Julia processes

---

scripts/packages/VSCodeServer/src/eval.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/3439.
Changes tested in the debug mode on 1.9.3 and 1.10-beta3.
Code mirrors what has been applied for `err` previously.

Fix `ans` to write to MainInclude.ans for Julia 1.10+

---

src/interactive/repl.ts

It's called "Output" not "Outputs".

Fix error message typo

---

src/notebook/notebookKernel.ts

Fixes a very minor typo in one of the output messages. Change seemed too minor to be worth including in the changelog, but I can add it if it's preferable.

Fix minor typo 'starting'

---

src/juliaexepath.ts

We had a couple of reports where folks launch VS Code on MacOS from the graphical finder UI, and that seems to end up with a VS Code process that doesn't have the Juliaup `PATH` modifications. This seems one easy way here to fix this. I haven't tested it, though...

Run the Juliaup detection in a shell on Mac/Linux

---

CHANGELOG.md
package.json

On many keyboards (well at least mine) the combination Alt + I is used to type the |  (pipe symbol), which is important julia syntax. @pfitzseb
Fixes #.

change Alt + I to Alt + J

---

scripts/packages/VSCodeServer/src/VSCodeServer.jl

Removing what seems to be a duplicate assignment inside the `serve` function
- No change in doc/functionality
- Not worth mentioning in the changelog

remove code duplication

---

scripts/packages/VSCodeServer/src/display.jl

Fixes #3511.
For some complicated types (esp. SciML/DifferentialEquations.jl solutions), the result can takes very long to show in the REPL after computation is done. This PR applies `@nospecialize` on the displayed variable to get around the slowdown.
Reference:
in julia, the display functions have the `@nospecialize` tag
https://github.com/JuliaLang/julia/blob/4919dd79dfd848eb6d9929768666977f374c7f10/base/multimedia.jl#L228-L229

display with `@nospecialize`

---

.github/pull_request_template.md
.github/workflows/changelog.yml
.github/workflows/release.yml
.github/workflows/test-extension.yml
.github/workflows/test-julia.yml

This PR adds a https://github.com/marketplace/actions/changelog-enforcer workflow to ensure the changelog is kept updated.
It also splits up the various kinds of workflows (test extension, test julia packages, handle releases) into separate files and only runs them on demand (hopefully).

ci: enforce changelog diffs in PRs and split workflow up

---

CHANGELOG.md
package-lock.json
package.json
src/docbrowser/documentation.ts
src/notebook/notebookFeature.ts
src/scripts/updateDeps.ts
tsconfig.json

Currently whenever one opens a Julia notebook it is marked as edited because we always apply an edit that updates the metadata. With this PR we check whether any metadata has actually changed, and only then update the metadata.

Only update notebook metadata when stale

---

package-lock.json
scripts/environments/development/Manifest.toml
scripts/environments/languageserver/fallback/Manifest.toml
scripts/environments/languageserver/v1.0/Manifest.toml
scripts/environments/languageserver/v1.1/Manifest.toml
scripts/environments/languageserver/v1.10/Manifest.toml
scripts/environments/languageserver/v1.2/Manifest.toml
scripts/environments/languageserver/v1.3/Manifest.toml
scripts/environments/languageserver/v1.4/Manifest.toml
scripts/environments/languageserver/v1.5/Manifest.toml
scripts/environments/languageserver/v1.6/Manifest.toml
scripts/environments/languageserver/v1.7/Manifest.toml
scripts/environments/languageserver/v1.8/Manifest.toml
scripts/environments/languageserver/v1.9/Manifest.toml
scripts/environments/pkgdev/fallback/Manifest.toml
scripts/environments/pkgdev/v1.6/Manifest.toml
scripts/environments/pkgdev/v1.7/Manifest.toml
scripts/environments/pkgdev/v1.8/Manifest.toml
scripts/environments/pkgdev/v1.9/Manifest.toml
scripts/environments/sysimagecompile/fallback/Manifest.toml
src/scripts/updateDeps.ts

Now that Juliaup has support for a nightly channel we can have the fallback environment work for nightly builds. Won't be perfect because we still have to trigger it manually, but it should be fairly easy now to push out a build that supports the latest Julia nightly build in terms of the environments we use.

Use nightly build for fallback env

---

CHANGELOG.md
package.json
src/interactive/repl.ts

Fixes https://github.com/JuliaDebug/Cthulhu.jl/issues/542.
cc @Zentrik

fix: disable static hints when runtime hints are displayed

---

CHANGELOG.md
scripts/debugger/run_debugger.jl
scripts/notebook/notebook.jl
scripts/terminalserver/terminalserver.jl
scripts/testserver/testserver_main.jl
src/interactive/repl.ts

Avoids #3542 from happening again.
I just editted this in Github so this will definately need squashing.

Always popfirst the load path, even if using fails

---

CHANGELOG.md
scripts/packages/VSCodeLiveUnitTesting/src/VSCodeLiveUnitTesting.jl
scripts/packages/VSCodeTestServer/src/pkg_imports.jl

In https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/598 `is_GotoIfNot` and `is_ReturnNode` were removed. With #3531 we started using JuliaInterpreter 0.9.28 which includes this change. This breaks the Julia test server:
```
Info: Starting the Julia Test Server
ERROR: LoadError: UndefVarError: `is_GotoIfNot` not defined
Stacktrace:
[1] include(mod::Module, _path::String)
@ Base .\Base.jl:495
[2] include(x::String)
@ VSCodeTestServer c:\Users\visser_mn\.vscode\extensions\julialang.language-julia-1.71.1\scripts\packages\VSCodeTestServer\src\VSCodeTestServer.jl:1
```
With this change, that is fixed. These two functions are not used in this repo or its submodules.
The removal of these functions also caused #3526 but I think that has already been fixed by using a newer Revise version, so …

Remove imports of removed JuliaInterpreter functions

---

CHANGELOG.md
src/notebook/notebookFeature.ts

Future proofing access to notebook metadata

---

.github/workflows/main.yml

Alternative to #3584.
Fixes #.

CI: Run CI on Julia 1.11, and migrate to `julia-actions/install-juliaup`

---

CHANGELOG.md
scripts/packages/VSCodeServer/src/misc.jl

Fixes https://github.com/julia-vscode/julia-vscode/issues/3580.

fix: make backtrace pruning work on 1.12

---

CHANGELOG.md
scripts/packages/VSCodeServer/src/profiler.jl

Stopped passing additional keywords to make_tree when calling @profview. 
Fixes
```jl
@profview f(x) recur=:flat
```

Fix optional arguments of @profview

---

CHANGELOG.md
src/notebook/notebookFeature.ts

For https://github.com/microsoft/vscode/issues/227419
- [N/A] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
@davidanthoff Given that the Notebook API in VS Code is now stable, we can start using that instead of the private extension specific API added.
The plan is to get this merged, and once you have shipped a new version of the Julia extension we can then remove the other internal API `vscodeIpynbApi.setNotebookMetadata` (perhaps in another month or two, giving enough time for Julia extension to adopt and publish the changes)

Use stable VS Code API to edit notebook metadata

---

CHANGELOG.md
src/interactive/plots.ts

As discussed on slack, verified works locally.
Fixes https://github.com/JuliaPlots/PlotlyJS.jl/issues/444

Pass `config` field to Plotly.newPlot call

---

CHANGELOG.md
src/scripts/updateDeps.ts

The bundled *plotly.js* is now 3 years old (last updated by #2376).
While the plots made for the new versions of plotly still could be displayed in principle, some new features (e.g. shape labels, tick labels) are not displayed.
This PR brings it to 2.35.2.
The *plotly.min.js* is taken as is from https://cdn.plot.ly/plotly-2.35.2.min.js.
Also added `plotly.min.js` support to *updateDeps.ts* scripts to make these updates automatic.

Update plotly.js to 2.35.2

---

scripts/languageserver/main.jl

Limit log output during debug runs for the LS

---

src/telemetry.ts

This should allow us to catch more unhandled exceptions.

Tap into crash reports from the VS Code telemetry logger

---

CHANGELOG.md
scripts/plots/main_plot_webview.js
src/interactive/plots.ts

The "save plot" button was not working for Makie plots ever since Makie started to show them via html MIME types, as the png MIME type doesn't show them at the intended pixel density. This PR wraps html content in an id'ed div so the plot detection code can pick that up and extract a possible single `<img>` tag. With that, the existing code works for the Makie case as well.
Also, I had trouble with the "copy plot to clipboard" functionality for a long time, so while I was at it, I looked into improving that as well. It seems that the focus check for clipboard access often fails because of a race condition inherent in this system, so apparently adding a small timeout improves that https://stackoverflow.com/questions/77465342/how-do-i-ensure-that-the-website-has-focus-so-the-copy-to-clipboar …

Allow saving for Makie png/html plots and improve clipboard behavior

---

CHANGELOG.md
package.json
src/extension.ts
src/juliaexepath.ts

This addresses a use case where a user might want to set a different julia executable path for language server specifically.
One example is that the user might want to always launch julia repl with a specific sysimage, but they want the language server not to use that sysimage, but just plain julia.
Docs https://github.com/julia-vscode/docs/pull/92

feat: add a configurable julia executable path for language server

---

CHANGELOG.md
package.json

This adds the other Literate.jl delimiters for markdown to the default setting for cellDelimiters in addition to the one added in #2566.
```julia
```

Add Literate.jl headers to cellDelimiters

---

package.json

Fixes a few typos in `package.json` options descriptions.
- [x ] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.

fix typos in package.json
